let flashcards = [
  { wordToGuess: "abecedario, el", hint: "abeceda", category: ["podstatnaJm"] },
  { wordToGuess: "abogado/a, el/la", hint: "právník", category: ["profese"] },
  { wordToGuess: "actuar", hint: "hrát, vystupovat", category: ["cinnost"] },
  { wordToGuess: "adecuado/a", hint: "adekvátní", category: ["pridavnaJm"] },
  { wordToGuess: "adivinar", hint: "hádat", category: ["slovesa"] },
  { wordToGuess: "afirmación, la", hint: "potvrzení", category: ["podstatnaJm"] },
  { wordToGuess: "ahora", hint: "teď", category: ["cas"] },
  { wordToGuess: "aire, el", hint: "vzduch", category: ["podstatnaJm"] },
  { wordToGuess: "alto/a", hint: "vysoký", category: ["pridavnaJm"] },
  { wordToGuess: "amigo/a, el/la", hint: "kamarád", category: ["podstatnaJm"] },
  { wordToGuess: "animal, el", hint: "zvíře", category: ["podstatnaJm"] },
  { wordToGuess: "antes (de)", hint: "před", category: ["umisteni"] },
  { wordToGuess: "añadir", hint: "přidat", category: ["cinnost"] },
  { wordToGuess: "aparecer", hint: "zdát se, objevit se", category: ["cinnost"] },
  { wordToGuess: "apellido, el", hint: "příjmení", category: ["podstatnaJm"] },
  { wordToGuess: "aquí", hint: "tady", category: ["umisteni"] },
  { wordToGuess: "Argentina", hint: "Argentina", category: ["zeme"] },
  { wordToGuess: "argentino/a", hint: "Argentinec", category: ["zeme"] },
  { wordToGuess: "arquitecto/a, el/la", hint: "architekt", category: ["profese"] },
  { wordToGuess: "artista, el/la", hint: "umělec", category: ["profese"] },
  { wordToGuess: "así", hint: "tak" },
  { wordToGuess: "aunque", hint: "ačkoliv, přestože" },
  { wordToGuess: "ayudar", hint: "pomoct", category: ["cinnost"] },
  { wordToGuess: "bandeja, la", hint: "tác, podnos", category: ["podstatnaJm"] },
  { wordToGuess: "bandera, la", hint: "vlajka", category: ["podstatnaJm"] },
  { wordToGuess: "bar, el", hint: "bar", category: ["profese"] },
  { wordToGuess: "bien", hint: "dobře", category: ["pridavnaJm "] },
  { wordToGuess: "billete, el", hint: "lístek, jízdenka", category: ["podstatnaJm"] },
  { wordToGuess: "blanco/a", hint: "bílý", category: ["pridavnaJm", "barvy"] },
  { wordToGuess: "botella, la", hint: "láhev", category: ["podstatnaJm"] },
  { wordToGuess: "Brasil", hint: "Brazílie", category: ["zeme"] },
  { wordToGuess: "Brasileño/a", hint: "Brazilec", category: ["zeme"] },
  { wordToGuess: "bueno/a", hint: "dobrý", category: ["pridavnaJm"] },
  { wordToGuess: "cada", hint: "každý", category: ["pridavnaJm"] },
  { wordToGuess: "cadena, la", hint: "řetěz", category: ["podstatnaJm"] },
  { wordToGuess: "caja, la", hint: "krabice", category: ["podstatnaJm"] },
  { wordToGuess: "calle, la", hint: "ulice", category: ["podstatnaJm", "mista"] },
  { wordToGuess: "cámara, la", hint: "fotoaparát", category: ["cinnost"] },
  { wordToGuess: "camarero/a, el/la", hint: "číšník", category: ["profese"] },
  { wordToGuess: "capital, la", hint: "hlavní město", category: ["mista"] },
  { wordToGuess: "casco, el", hint: "historické centrum, helma", category: ["mista"] },
  { wordToGuess: "casilla, la", hint: "rámeček, mezera", category: ["podstatnaJm"] },
  { wordToGuess: "castaño/a", hint: "hnědý", category: ["barvy"] },
  { wordToGuess: "Chile", hint: "Chile", category: ["zeme"] },
  { wordToGuess: "chileno/a", hint: "Chilan", category: ["zeme"] },
  { wordToGuess: "ciudad, la", hint: "město", category: ["mista"] },
  { wordToGuess: "claro/a", hint: "jasný, světlý", category: ["pridavnaJm"] },
  { wordToGuess: "clase, la", hint: "třída", category: ["podstatnaJm", "mista"] },
  { wordToGuess: "clínica, la", hint: "klinika", category: ["profese", "mista"] },
  { wordToGuess: "coche, el", hint: "auto", category: ["podstatnaJm"] },
  { wordToGuess: "cocinero/a, el/la", hint: "kuchař", category: ["profese"] },
  { wordToGuess: "Colombia", hint: "Kolumbie", category: ["zeme"] },
  { wordToGuess: "colombiano/a", hint: "Kolumbijec", category: ["zeme"] },
  { wordToGuess: "cómo", hint: "jak", category: ["zajmeno"] },
  {
    wordToGuess: "compañero/a, el/la",
    hint: "kamarád, spolužák (de clase)",
    category: ["podstatnaJm"],
  },
  { wordToGuess: "completo/a", hint: "kompletní", category: ["pridavnaJm"] },
  { wordToGuess: "confirmar", hint: "potvrdit", category: ["cinnost"] },
  { wordToGuess: "congreso, el", hint: "kongres", category: ["podstatnaJm"] },
  { wordToGuess: "conocer", hint: "vědět, znát", category: ["cinnost"] },
  { wordToGuess: "contestar", hint: "odpovědět", category: ["cinnost"] },
  { wordToGuess: "correcto/a", hint: "správný", category: ["pridavnaJm"] },
  { wordToGuess: "corregir", hint: "opravit", category: ["cinnost"] },
  { wordToGuess: "corresponder", hint: "odpovědět", category: ["cinnost"] },
  { wordToGuess: "correspondiente", hint: "odpovídající", category: ["pridavnaJm"] },
  { wordToGuess: "cuadro, el", hint: "obrázek", category: ["podstatnaJm"] },
  { wordToGuess: "cuál", hint: "jaký, který", category: ["zajmeno"] },
  { wordToGuess: "cuanto", hint: "kolik", category: ["zajmeno", "cisla"] },
  { wordToGuess: "cuatro", hint: "4", category: ["cisla"] },
  { wordToGuess: "cultural", hint: "kulturní", category: ["pridavnaJm"] },
  { wordToGuess: "dar", hint: "dát", category: ["cinnost"] },
  { wordToGuess: "dato, el", hint: "datum", category: ["cas"] },
  { wordToGuess: "dedicar", hint: "věnovat, dedikovat", category: ["cinnost"] },
  { wordToGuess: "delante (de)", hint: "před", category: ["umisteni"] },
  { wordToGuess: "deletrear", hint: "vyhláskovat", category: ["cinnost"] },
  { wordToGuess: "derecha, la", hint: "pravý", category: ["umisteni"] },
  { wordToGuess: "después (de)", hint: "po", category: ["zajmeno"] },
  { wordToGuess: "diálogo, el", hint: "dialog", category: ["podstatnaJm"] },
  { wordToGuess: "día, el", hint: "den", category: ["cas", "podstatnaJm"] },
  { wordToGuess: "dibujo, el", hint: "obrázek", category: ["podstatnaJm"] },
  { wordToGuess: "distinguir", hint: "odlišit", category: ["cinnost"] },
  { wordToGuess: "distinto/a", hint: "odlišný", category: ["pridavnaJm"] },
  { wordToGuess: "domicilio, el", hint: "bydliště", category: ["mista"] },
  { wordToGuess: "dónde", hint: "kde", category: ["zajmeno"] },
  { wordToGuess: "Ecuador", hint: "Ekvádor", category: ["zeme"] },
  { wordToGuess: "ejemplo, el", hint: "příklad", category: ["podstatnaJm"] },
  { wordToGuess: "ejercicio, el", hint: "cvičení", category: ["podstatnaJm"] },
  { wordToGuess: "empleado/a, el/la", hint: "zaměstnanec", category: ["podstatnaJm", "profese"] },
  { wordToGuess: "empresa, la", hint: "firma", category: ["podstatnaJm", "mista", "profese "] },
  { wordToGuess: "entre", hint: "mezi", category: ["umisteni"] },
  { wordToGuess: "entrevista, la", hint: "rozhovor", category: ["cinnost"] },
  { wordToGuess: "entrevistador/a, el/la", hint: "dotazovatel", category: ["profese"] },
  { wordToGuess: "escuela, la", hint: "škola", category: ["podstatnaJm", "mista"] },
  { wordToGuess: "España", hint: "Španělsko", category: ["zeme"] },
  { wordToGuess: "español/-a", hint: "Španěl", category: ["zeme"] },
  { wordToGuess: "estadounidense", hint: "z USA", category: ["zeme"] },
  { wordToGuess: "estudiante, el/la", hint: "student", category: ["profese"] },
  { wordToGuess: "estudiar", hint: "studovat", category: ["profese"] },
  { wordToGuess: "famoso/a", hint: "známý", category: ["pridavnaJm"] },
  { wordToGuess: "femenino/a", hint: "ženský", category: ["pridavnaJm"] },
  { wordToGuess: "ficha, la", hint: "formulář", category: ["podstatnaJm"] },
  { wordToGuess: "fontanero/a, el/la", hint: "instalatér", category: ["profese"] },
  { wordToGuess: "forma, la", hint: "forma", category: ["podstatnaJm"] },
  { wordToGuess: "foto, la", hint: "fotka", category: ["podstatnaJm"] },
  { wordToGuess: "frase, la", hint: "věta", category: ["podstatnaJm"] },
  { wordToGuess: "gente, la", hint: "lidé", category: ["podstatnaJm"] },
  { wordToGuess: "gorra, la", hint: "čepice", category: ["podstatnaJm"] },
  { wordToGuess: "gracias", hint: "děkuji", category: ["podstatnaJm"] },
  { wordToGuess: "Grecia", hint: "Řecko", category: ["zeme"] },
  { wordToGuess: "griego/a", hint: "Řek", category: ["zeme"] },
  { wordToGuess: "grupo, el", hint: "skupina", category: ["podstatnaJm"] },
  { wordToGuess: "gustar", hint: "mít rád", category: ["cinnost"] },
  { wordToGuess: "habitante, el", hint: "obyvatel", category: ["zeme"] },
  { wordToGuess: "hablar", hint: "mluvit", category: ["cinnost"] },
  { wordToGuess: "hasta", hint: "až do", category: ["cas"] },
  { wordToGuess: "hay", hint: "je, existuje", category: ["zajmeno"] },
  { wordToGuess: "herramienta, la", hint: "nástroj", category: ["podstatnaJm"] },
  { wordToGuess: "hispanoamérica", hint: "Latinská Amerika", category: ["zeme"] },
  { wordToGuess: "hola", hint: "ahoj", category: ["podstatnaJm"] },
  { wordToGuess: "hospital, el", hint: "nemocnice", category: ["podstatnaJm", "profese", "mista"] },
  { wordToGuess: "hotel, el", hint: "hotel", category: ["podstatnaJm", "mista", "profese"] },
  { wordToGuess: "identificación, la", hint: "identifikace", category: ["cinnost"] },
  { wordToGuess: "idioma, el", hint: "jazyk", category: ["podstatnaJm"] },
  { wordToGuess: "igual", hint: "stejný", category: ["pridavnaJm"] },
  { wordToGuess: "importante", hint: "důležitý", category: ["pridavnaJm"] },
  { wordToGuess: "información, la", hint: "informace", category: ["podstatnaJm"] },
  { wordToGuess: "informador/-a, el/la", hint: "informátor, zpravodaj", category: ["profese"] },
  { wordToGuess: "inglés/a", hint: "Angličan", category: ["zeme"] },
  { wordToGuess: "integrado/a", hint: "začleněný", category: ["pridavnaJm"] },
  { wordToGuess: "intentar", hint: "zkusit", category: ["cinnost"] },
  { wordToGuess: "internacional", hint: "mezinárodní", category: ["zeme"] },
  { wordToGuess: "interrogación, la", hint: "otázka", category: ["podstatnaJm"] },
  { wordToGuess: "inventar", hint: "vymyslet, vytvořit", category: ["cinnost"] },
  { wordToGuess: "iraní", hint: "Íránec", category: ["zeme"] },
  { wordToGuess: "Italia", hint: "Itálie", category: ["zeme"] },
  { wordToGuess: "italiano/a", hint: "Ital", category: ["zeme"] },
  { wordToGuess: "izquierda, la", hint: "levý", category: ["umisteni", "pridavnaJm"] },
  { wordToGuess: "japonés/-a", hint: "Japonec", category: ["zeme"] },
  { wordToGuess: "lengua, la", hint: "jazyk", category: ["podstatnaJm"] },
  { wordToGuess: "letra, la", hint: "písmeno", category: ["podstatnaJm"] },
  { wordToGuess: "mano, la", hint: "ruka", category: ["podstatnaJm"] },
  { wordToGuess: "mapa, el", hint: "mapa", category: ["podstatnaJm"] },
  { wordToGuess: "marca, la", hint: "značka, stopa", category: ["podstatnaJm"] },
  { wordToGuess: "mal", hint: "špantně", category: ["pridavnaJm"] },
  { wordToGuess: "más", hint: "více", category: ["pridavnaJm"] },
  { wordToGuess: "masculino/a", hint: "mužský", category: ["pridavnaJm"] },
  { wordToGuess: "médico/a", hint: "lékař", category: ["profese"] },
  { wordToGuess: "mencionar", hint: "zmínit", category: ["cinnost"] },
  { wordToGuess: "mexicano/a", hint: "Mexičan", category: ["zeme"] },
  { wordToGuess: "México", hint: "Mexiko", category: ["zeme"] },
  { wordToGuess: "micrófono, el", hint: "mikrofon", category: ["podstatnaJm"] },
  { wordToGuess: "muy", hint: "velmi", category: ["pridavnaJm"] },
  { wordToGuess: "nacionalidad, la", hint: "národnost", category: ["zeme"] },
  { wordToGuess: "Nicaragua", hint: "Nicaragua", category: ["zeme"] },
  { wordToGuess: "Nicaragüense", hint: "Nikaragujec", category: ["zeme"] },
  { wordToGuess: "nombre, el", hint: "jméno", category: ["podstatnaJm"] },
  { wordToGuess: "norteamericano/a", hint: "Severoameričan", category: ["zeme"] },
  { wordToGuess: "nuevo/a", hint: "nový", category: ["pridavnaJm"] },
  { wordToGuess: "objeto, el", hint: "objekt", category: ["podstatnaJm"] },
  { wordToGuess: "ocupación, la", hint: "činnost, aktivita", category: ["profese"] },
  { wordToGuess: "ocupar", hint: "zabývat se, zaměstnat", category: ["profese"] },
  { wordToGuess: "oficial", hint: "oficiální", category: ["pridavnaJm"] },
  { wordToGuess: "oficina, la", hint: "kancelář", category: ["mista", "profese"] },
  { wordToGuess: "oído, el", hint: "sluch", category: ["podstatnaJm"] },
  { wordToGuess: "opción, la", hint: "možnost", category: ["podstatnaJm"] },
  { wordToGuess: "ordenar", hint: "srovnat, seřadit", category: ["cinnost"] },
  { wordToGuess: "otro/a", hint: "jiný, další", category: ["pridavnaJm"] },
  { wordToGuess: "paciente, el", hint: "pacient", category: ["profese"] },
  { wordToGuess: "país, el", hint: "stát", category: ["cinnost"] },
  { wordToGuess: "palabra, la", hint: "slovo", category: ["podstatnaJm"] },
  { wordToGuess: "para", hint: "aby, pro", category: ["zajmeno "] },
  { wordToGuess: "pareja, la", hint: "partner", category: ["podstatnaJm"] },
  { wordToGuess: "paréntesis, el", hint: "závorky", category: ["podstatnaJm"] },
  { wordToGuess: "participante, el", hint: "účastník", category: ["podstatnaJm"] },
  { wordToGuess: "pedir", hint: "prosit, žádat", category: ["cinnost"] },
  { wordToGuess: "peluquería, la", hint: "kadeřnictví", category: ["mista", "profese"] },
  { wordToGuess: "peluquero/a, el/la", hint: "kadeřník", category: ["profese"] },
  { wordToGuess: "pequeño/a", hint: "malý", category: ["pridavnaJm"] },
  { wordToGuess: "perfecto/a", hint: "perfektní", category: ["pridavnaJm"] },
  { wordToGuess: "periódico, el", hint: "noviny", category: ["podstatnaJm", "profese"] },
  { wordToGuess: "periodismo, el", hint: "novinařina", category: ["profese"] },
  { wordToGuess: "periodista, el/la", hint: "novinář", category: ["profese"] },
  { wordToGuess: "pero", hint: "ale", category: ["zajmeno"] },
  { wordToGuess: "perro, el", hint: "pes", category: ["podstatnaJm"] },
  { wordToGuess: "persona, la", hint: "osoba", category: ["podstatnaJm"] },
  { wordToGuess: "personal", hint: "personál", category: ["podstatnaJm", "profese"] },
  { wordToGuess: "personalidad, la", hint: "osobnost", category: ["podstatnaJm"] },
  { wordToGuess: "Perú", hint: "Peru", category: ["zeme"] },
  { wordToGuess: "peruano/a", hint: "Peruánec", category: ["zeme"] },
  { wordToGuess: "pintor/-a, el/la", hint: "malíř", category: ["profese"] },
  { wordToGuess: "piso, el", hint: "byt", category: ["podstatnaJm", "mista"] },
  { wordToGuess: "pizarra, la", hint: "tabule", category: ["podstatnaJm"] },
  { wordToGuess: "pizzería, la", hint: "pizzerie", category: ["podstatnaJm", "mista", "profese"] },
  { wordToGuess: "plano, el", hint: "plán", category: ["podstatnaJm"] },
  { wordToGuess: "población, la", hint: "osídlení, populace", category: ["podstatnaJm"] },
  { wordToGuess: "policía, la", hint: "policie", category: ["profese"] },
  { wordToGuess: "practicar", hint: "cvičit, praktikovat", category: ["cinnost"] },
  { wordToGuess: "pregunta, la", hint: "otázka", category: ["podstatnaJm"] },
  { wordToGuess: "preguntar", hint: "ptát se", category: ["cinnost"] },
  { wordToGuess: "presentar", hint: "představit", category: ["cinnost"] },
  { wordToGuess: "principio, el", hint: "začátek", category: ["podstatnaJm", "cas"] },
  { wordToGuess: "profesión, la", hint: "profese", category: ["profese"] },
  { wordToGuess: "profesor/-a, el/la", hint: "professor, učitel", category: ["profese"] },
  { wordToGuess: "pues", hint: "nuže, tak tedy", category: ["zajmeno"] },
  { wordToGuess: "punto, el", hint: "bod, tečka", category: ["podstatnaJm"] },
  { wordToGuess: "puntuación, la", hint: "interpunkce", category: ["podstatnaJm"] },
  { wordToGuess: "puntuar", hint: "obodovat", category: ["cinnost"] },
  { wordToGuess: "que", hint: "co", category: ["zajmeno"] },
  { wordToGuess: "reconocer", hint: "poznat", category: ["cinnost"] },
  { wordToGuess: "región, la", hint: "region", category: ["podstatnaJm", "mista"] },
  { wordToGuess: "relacionar", hint: "spojit", category: ["cinnost"] },
  { wordToGuess: "rellenar", hint: "vyplnit", category: ["cinnost"] },
  { wordToGuess: "responder", hint: "odpovědět", category: ["cinnost"] },
  { wordToGuess: "respuesta, la", hint: "odpověď", category: ["podstatnaJm"] },
  { wordToGuess: "restaurante, el", hint: "restaurace", category: ["mista", "profese"] },
  { wordToGuess: "saludar", hint: "pozdravit", category: ["cinnost"] },
  { wordToGuess: "significado, el", hint: "význam", category: ["podstatnaJm"] },
  { wordToGuess: "signo, el", hint: "znamení", category: ["podstatnaJm"] },
  { wordToGuess: "sin", hint: "bez", category: ["zajmeno"] },
  { wordToGuess: "sobre", hint: "o, na", category: ["zajmeno"] },
  { wordToGuess: "también", hint: "taky", category: ["zajmeno"] },
  { wordToGuess: "tarjeta, la", hint: "karta", category: ["podstatnaJm"] },
  { wordToGuess: "taxista, el/la", hint: "taxikář", category: ["profese"] },
  { wordToGuess: "tenista, el/la", hint: "tenista", category: ["profese"] },
  { wordToGuess: "termómetro, el", hint: "teploměr", category: ["podstatnaJm"] },
  { wordToGuess: "texto, el", hint: "text", category: ["podstatnaJm"] },
  { wordToGuess: "tiqué, el", hint: "lístek", category: ["podstatnaJm"] },
  { wordToGuess: "tienda, la", hint: "obchod", category: ["mista", "profese"] },
  { wordToGuess: "tijeras, las", hint: "nůžky", category: ["podstatnaJm"] },
  { wordToGuess: "todavía", hint: "ještě", category: ["zajmeno"] },
  { wordToGuess: "todo", hint: "vše", category: ["cisla"] },
  { wordToGuess: "trabajar", hint: "pracovat", category: ["cinnost"] },
  { wordToGuess: "trabajo, el", hint: "práce", category: ["cinnost", "profese"] },
  { wordToGuess: "tratar", hint: "pokusit se, snažit se", category: ["cinnost"] },
  { wordToGuess: "universidad, la", hint: "univerzita", category: ["mista"] },
  { wordToGuess: "usar", hint: "použít", category: ["cinnost"] },
  { wordToGuess: "vaso, el", hint: "sklenice", category: ["podstatnaJm"] },
  { wordToGuess: "vendedor/-a, el/la", hint: "prodavač", category: ["profese"] },
  { wordToGuess: "venezolano/a", hint: "Venezolan", category: ["zeme"] },
  { wordToGuess: "Venezuela", hint: "Venezuela", category: ["zeme"] },
  { wordToGuess: "verbo, el", hint: "sloveso", category: ["podstatnaJm"] },
  { wordToGuess: "veterinario/a", hint: "veterinář", category: ["profese"] },
  { wordToGuess: "vivir", hint: "žít", category: ["cinnost"] },
  { wordToGuess: "voz, la", hint: "hlas", category: ["podstatnaJm"] },
  { wordToGuess: "zoo(lógico), el", hint: "zoo", category: ["mista", "profese"] },
  { wordToGuess: "Rojo", hint: "červená", category: ["barvy"] },
  { wordToGuess: "Azul", hint: "Modrá", category: ["barvy"] },
  { wordToGuess: "Verde", hint: "Zelená", category: ["barvy"] },
  { wordToGuess: "Las frutas", hint: "Ovoce", category: ["jidlo"] },
  { wordToGuess: "Las manzanas", hint: "Jablka", category: ["jidlo"] },
  { wordToGuess: "Los melocotones", hint: "Broskve", category: ["jidlo"] },
  { wordToGuess: "Los limones", hint: "Citrony", category: ["jidlo"] },
  { wordToGuess: "Las fresas", hint: "Jahody", category: ["jidlo"] },
  { wordToGuess: "Las cerezas", hint: "Třešně", category: ["jidlo"] },
  { wordToGuess: "La sandía", hint: "Meloun (vodní)", category: ["jidlo"] },
  { wordToGuess: "Los plátanos", hint: "Banány", category: ["jidlo"] },
  { wordToGuess: "La piña", hint: "Ananas", category: ["jidlo"] },
  { wordToGuess: "El melón", hint: "Meloun (cukrový)", category: ["jidlo"] },
  { wordToGuess: "Las castañas", hint: "Kaštany", category: ["jidlo"] },
  { wordToGuess: "La uva", hint: "Hroznové víno", category: ["jidlo"] },
  { wordToGuess: "Los higos", hint: "Fíky", category: ["jidlo"] },
  { wordToGuess: "Las naranjas", hint: "Pomeranče", category: ["jidlo"] },
  { wordToGuess: "Las peras", hint: "Hrušky", category: ["jidlo"] },
  { wordToGuess: "Las mandarinas", hint: "Mandarinky", category: ["jidlo"] },
  { wordToGuess: "Las verduras", hint: "Zelenina", category: ["jidlo"] },
  { wordToGuess: "El pepino", hint: "Okurka", category: ["jidlo"] },
  { wordToGuess: "La lechuga", hint: "Hlávkový salát", category: ["jidlo"] },
  { wordToGuess: "Las zanahorias", hint: "Mrkve", category: ["jidlo"] },
  { wordToGuess: "Los tomates", hint: "Rajčata", category: ["jidlo"] },
  { wordToGuess: "Las cebollas", hint: "Cibule", category: ["jidlo"] },
  { wordToGuess: "Los calabacines", hint: "Cukety", category: ["jidlo"] },
  { wordToGuess: "Los pimientos", hint: "Papriky", category: ["jidlo"] },
  { wordToGuess: "Las patatas", hint: "Brambory", category: ["jidlo"] },
  { wordToGuess: "El arroz", hint: "Rýže", category: ["jidlo"] },
  { wordToGuess: "Los ajos", hint: "Česnek", category: ["jidlo"] },
  { wordToGuess: "Los guisantes", hint: "Hrášek", category: ["jidlo"] },
  { wordToGuess: "Las coles", hint: "Zelí", category: ["jidlo"] },
  { wordToGuess: "Las judías verdes", hint: "Zelené fazolky", category: ["jidlo"] },
  { wordToGuess: "Las berenjenas", hint: "Lilek", category: ["jidlo"] },
  { wordToGuess: "La calabaza", hint: "Dýně", category: ["jidlo"] },
  { wordToGuess: "La carne y los embutidos", hint: "Maso a uzeniny", category: ["jidlo"] },
  { wordToGuess: "El jamón", hint: "Šunka", category: ["jidlo"] },
  { wordToGuess: "El salchichón", hint: "Salám", category: ["jidlo"] },
  { wordToGuess: "Las salchichas", hint: "Párečky", category: ["jidlo"] },
  { wordToGuess: "La carne de vaca", hint: "Hovězí maso", category: ["jidlo"] },
  { wordToGuess: "La carne de ternera", hint: "Telecí maso", category: ["jidlo"] },
  { wordToGuess: "La carne de cerdo", hint: "Vepřové maso", category: ["jidlo"] },
  { wordToGuess: "La carne de cordero", hint: "Jehněčí maso", category: ["jidlo"] },
  { wordToGuess: "La carne de pollo", hint: "Kuřecí maso", category: ["jidlo"] },
  { wordToGuess: "El pescado", hint: "Ryby", category: ["jidlo"] },
  { wordToGuess: "La carpa", hint: "Kapr", category: ["jidlo"] },
  { wordToGuess: "El lucio", hint: "Štika", category: ["jidlo"] },
  { wordToGuess: "La anguila", hint: "Úhoř", category: ["jidlo"] },
  { wordToGuess: "La trucha", hint: "Pstruh", category: ["jidlo"] },
  { wordToGuess: "El salmón", hint: "Losos", category: ["jidlo"] },
  { wordToGuess: "La merluza", hint: "Mořská štika", category: ["jidlo"] },
  { wordToGuess: "El atún", hint: "Tuňák", category: ["jidlo"] },
  { wordToGuess: "Los pulpos", hint: "Chobotnice", category: ["jidlo"] },
  { wordToGuess: "Las sepias", hint: "Sépie", category: ["jidlo"] },
  { wordToGuess: "Los langostinos", hint: "Krevety (tygří)", category: ["jidlo"] },
  { wordToGuess: "Los dulces", hint: "Sladkosti", category: ["jidlo"] },
  { wordToGuess: "El helado", hint: "Zmrzlina", category: ["jidlo"] },
  { wordToGuess: "El chocolate", hint: "Čokoláda", category: ["jidlo"] },
  { wordToGuess: "Los pasteles", hint: "Dortíky", category: ["jidlo"] },
  { wordToGuess: "Los caramelos", hint: "Bonbóny", category: ["jidlo"] },
  { wordToGuess: "Los bonbones", hint: "Pralinky", category: ["jidlo"] },
  { wordToGuess: "Los chupa-chups", hint: "Lízátka", category: ["jidlo"] },
  { wordToGuess: "Las tartas", hint: "Dorty", category: ["jidlo"] },
  { wordToGuess: "Los productos lácteos", hint: "Mléčné výrobky", category: ["jidlo"] },
  { wordToGuess: "La leche", hint: "Mléko", category: ["jidlo"] },
  { wordToGuess: "El yogúr", hint: "Jogurt", category: ["jidlo"] },
  { wordToGuess: "La mantequilla", hint: "Máslo", category: ["jidlo"] },
  { wordToGuess: "El queso", hint: "Sýr", category: ["jidlo"] },
  { wordToGuess: "La guarnición", hint: "Příloha", category: ["jidlo"] },
  { wordToGuess: "La ensalada", hint: "Salát", category: ["jidlo"] },
  { wordToGuess: "La pasta", hint: "Těstoviny", category: ["jidlo"] },
  { wordToGuess: "Los espaguetis", hint: "Špagety", category: ["jidlo"] },
  { wordToGuess: "Las croquetas", hint: "Krokety", category: ["jidlo"] },
  { wordToGuess: "Las bebidas", hint: "Nápoje", category: ["jidlo"] },
  { wordToGuess: "El zumo de naranja", hint: "Pomerančový džus", category: ["jidlo"] },
  { wordToGuess: "El zumo de manzana", hint: "Jablečný džus", category: ["jidlo"] },
  { wordToGuess: "El zumo de pera", hint: "Hruškový džus", category: ["jidlo"] },
  { wordToGuess: "El zumo de piña", hint: "Ananasový džus", category: ["jidlo"] },
  { wordToGuess: "El zumo de melocotón", hint: "Broskvový džus", category: ["jidlo"] },
  { wordToGuess: "El café", hint: "Káva", category: ["jidlo"] },
  { wordToGuess: "El café negro", hint: "Černá káva", category: ["jidlo"] },
  { wordToGuess: "El café con leche", hint: "Káva s mlékem", category: ["jidlo"] },
  { wordToGuess: "El chocolate", hint: "Horká čokoláda", category: ["jidlo"] },
  { wordToGuess: "La cerveza", hint: "Pivo", category: ["jidlo"] },
  { wordToGuess: "El vino blanco", hint: "Bílé víno", category: ["jidlo"] },
  { wordToGuess: "El vino tinto", hint: "Červené víno", category: ["jidlo"] },
  { wordToGuess: "El vino rosado", hint: "Růžové víno", category: ["jidlo"] },
  { wordToGuess: "El agua sin gas", hint: "Neperlivá voda", category: ["jidlo"] },
  { wordToGuess: "El agua con gas", hint: "Perlivá voda", category: ["jidlo"] },
  { wordToGuess: "El agua mineral", hint: "Minerální voda", category: ["jidlo"] },
  { wordToGuess: "El agua de grifo", hint: "Kohoutková voda", category: ["jidlo"] },
  { wordToGuess: "El refresco", hint: "Limonáda / nealko nápoj", category: ["jidlo"] },
  { wordToGuess: "La ropa", hint: "Oblečení", category: ["obleceni"] },
  { wordToGuess: "una falda", hint: "Sukně", category: ["obleceni"] },
  { wordToGuess: "un vestido", hint: "Šaty", category: ["obleceni"] },
  { wordToGuess: "un traje de fiesta", hint: "Společenský oblek/šaty", category: ["obleceni"] },
  { wordToGuess: "una blusa", hint: "Halenka", category: ["obleceni"] },
  { wordToGuess: "una camiseta", hint: "Tričko", category: ["obleceni"] },
  { wordToGuess: "una camisa", hint: "Košile", category: ["obleceni"] },
  { wordToGuess: "un jersey", hint: "Svetřík", category: ["obleceni"] },
  { wordToGuess: "un jersey de cuello alto", hint: "Rolák", category: ["obleceni"] },
  { wordToGuess: "un chaleco", hint: "Vesta", category: ["obleceni"] },
  { wordToGuess: "una sudadera", hint: "Mikina", category: ["obleceni"] },
  { wordToGuess: "un abrigo", hint: "Kabát", category: ["obleceni"] },
  { wordToGuess: "una chaqueta", hint: "Sako / bunda", category: ["obleceni"] },
  { wordToGuess: "una cazadora", hint: "Bunda (větrovka)", category: ["obleceni"] },
  { wordToGuess: "una gabardina", hint: "Plášť / trenčkot", category: ["obleceni"] },
  { wordToGuess: "una corbata", hint: "Kravata", category: ["obleceni"] },
  { wordToGuess: "un paňuelo", hint: "Šátek", category: ["obleceni"] },
  { wordToGuess: "una bufanda", hint: "Šála", category: ["obleceni"] },
  { wordToGuess: "una cinta", hint: "Stuha / čelenka", category: ["obleceni"] },
  { wordToGuess: "un chal", hint: "Šál / přehoz", category: ["obleceni"] },
  { wordToGuess: "un cinturón", hint: "Pásek", category: ["obleceni"] },
  { wordToGuess: "un sombrero", hint: "Klobouk", category: ["obleceni"] },
  { wordToGuess: "unas gafas de sol", hint: "Sluneční brýle", category: ["obleceni"] },
  { wordToGuess: "una gorra", hint: "Kšiltovka", category: ["obleceni"] },
  { wordToGuess: "unos guantes", hint: "Rukavice", category: ["obleceni"] },
  { wordToGuess: "un gorro", hint: "Čepice", category: ["obleceni"] },
  { wordToGuess: "una boina", hint: "Baskická čepice / baret", category: ["obleceni"] },
  { wordToGuess: "un traje", hint: "Oblek", category: ["obleceni"] },
  { wordToGuess: "un traje de chaqueta", hint: "Kostým / oblek se sakem", category: ["obleceni"] },
  { wordToGuess: "unos pantalones", hint: "Kalhoty", category: ["obleceni"] },
  { wordToGuess: "unos vaqueros", hint: "Džíny", category: ["obleceni"] },
  { wordToGuess: "unos pantalones cortos", hint: "Kraťasy", category: ["obleceni"] },
  { wordToGuess: "un chándal", hint: "Tepláková souprava", category: ["obleceni"] },
  { wordToGuess: "unos zapatos", hint: "Boty", category: ["obleceni"] },
  {
    wordToGuess: "unos zapatos de tacón",
    hint: "Lodičky / boty na podpatku",
    category: ["obleceni"],
  },
  { wordToGuess: "unas sandalias", hint: "Sandály", category: ["obleceni"] },
  { wordToGuess: "unas botas", hint: "Kozačky / boty", category: ["obleceni"] },
  { wordToGuess: "unas deportivas", hint: "Sportovní boty", category: ["obleceni"] },
  { wordToGuess: "unas zapatillas", hint: "Tenisky / pantofle", category: ["obleceni"] },
  { wordToGuess: "unos calcetines", hint: "Ponožky", category: ["obleceni"] },
  { wordToGuess: "unas medias", hint: "Punčochy", category: ["obleceni"] },
  { wordToGuess: "las joyas", hint: "Šperky", category: ["obleceni"] },
  { wordToGuess: "un collar", hint: "Náhrdelník", category: ["obleceni"] },
  { wordToGuess: "un anillo", hint: "Prsten", category: ["obleceni"] },
  { wordToGuess: "una cadena", hint: "Řetízek", category: ["obleceni"] },
  { wordToGuess: "una pulsera", hint: "Náramek", category: ["obleceni"] },
  { wordToGuess: "unos pendientes", hint: "Náušnice", category: ["obleceni"] },
];

const params = new URLSearchParams(window.location.search);
const selectedCategory = params.get("category");

if (selectedCategory) {
  const filtered = flashcards.filter(
    (flashcard) => flashcard.category && flashcard.category.includes(selectedCategory)
  );
  if (filtered.length > 2) {
    flashcards = filtered;
  }
}

function shuffle(array) {
  let currentIndex = array.length;

  // While there remain elements to shuffle...
  while (currentIndex != 0) {
    // Pick a remaining element...
    let randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;

    // And swap it with the current element.
    [array[currentIndex], array[randomIndex]] = [array[randomIndex], array[currentIndex]];
  }
}

shuffle(flashcards);

let currentIndex = 0;

const wordElement = document.getElementById("word");
const hintElement = document.getElementById("hint");
const prevButton = document.getElementById("prev");
const nextButton = document.getElementById("next");
const revealButton = document.getElementById("reveal");

// Function to update flashcard content
function updateFlashcard() {
  const currentCard = flashcards[currentIndex];
  wordElement.textContent = currentCard.wordToGuess;
  wordElement.style.visibility = "hidden"; // Hide the word initially
  hintElement.textContent = currentCard.hint;
}

// Event listeners for navigation
prevButton.addEventListener("click", () => {
  if (currentIndex > 0) {
    currentIndex--;
    updateFlashcard();
  }
});

nextButton.addEventListener("click", () => {
  if (currentIndex < flashcards.length - 1) {
    currentIndex++;
    updateFlashcard();
  }
});

// Event listener to reveal the word
revealButton.addEventListener("click", () => {
  wordElement.style.visibility = "visible";
});

// Initialize the flashcard
updateFlashcard();
