let flashcards = [
  { wordToGuess: "abecedario, el", hint: "abeceda", category: ["podstatnaJm"] },
  { wordToGuess: "abogado/a, el/la", hint: "právník", category: ["profese"] },
  { wordToGuess: "actuar", hint: "hrát, vystupovat", category: ["cinnost"] },
  { wordToGuess: "adecuado/a", hint: "adekvátní", category: ["pridavnaJm"] },
  { wordToGuess: "adivinar", hint: "hádat", category: ["slovesa"] },
  { wordToGuess: "afirmación, la", hint: "potvrzení", category: ["podstatnaJm"] },
  { wordToGuess: "ahora", hint: "teď", category: ["cas"] },
  { wordToGuess: "aire, el", hint: "vzduch", category: ["podstatnaJm"] },
  { wordToGuess: "alto/a", hint: "vysoký", category: ["pridavnaJm"] },
  { wordToGuess: "amigo/a, el/la", hint: "kamarád", category: ["podstatnaJm"] },
  { wordToGuess: "animal, el", hint: "zvíře", category: ["podstatnaJm"] },
  { wordToGuess: "antes (de)", hint: "před", category: ["umisteni"] },
  { wordToGuess: "añadir", hint: "přidat", category: ["cinnost"] },
  { wordToGuess: "aparecer", hint: "zdát se, objevit se", category: ["cinnost"] },
  { wordToGuess: "apellido, el", hint: "příjmení", category: ["podstatnaJm"] },
  { wordToGuess: "aquí", hint: "tady", category: ["umisteni"] },
  { wordToGuess: "Argentina", hint: "Argentina", category: ["zeme"] },
  { wordToGuess: "argentino/a", hint: "Argentinec", category: ["zeme"] },
  { wordToGuess: "arquitecto/a, el/la", hint: "architekt", category: ["profese"] },
  { wordToGuess: "artista, el/la", hint: "umělec", category: ["profese"] },
  { wordToGuess: "así", hint: "tak" },
  { wordToGuess: "aunque", hint: "ačkoliv, přestože" },
  { wordToGuess: "ayudar", hint: "pomoct", category: ["cinnost"] },
  { wordToGuess: "bandeja, la", hint: "tác, podnos", category: ["podstatnaJm"] },
  { wordToGuess: "bandera, la", hint: "vlajka", category: ["podstatnaJm"] },
  { wordToGuess: "bar, el", hint: "bar", category: ["profese"] },
  { wordToGuess: "bien", hint: "dobře", category: ["pridavnaJm "] },
  { wordToGuess: "billete, el", hint: "lístek, jízdenka", category: ["podstatnaJm"] },
  { wordToGuess: "blanco/a", hint: "bílý", category: ["pridavnaJm", "barvy"] },
  { wordToGuess: "botella, la", hint: "láhev", category: ["podstatnaJm"] },
  { wordToGuess: "Brasil", hint: "Brazílie", category: ["zeme"] },
  { wordToGuess: "Brasileño/a", hint: "Brazilec", category: ["zeme"] },
  { wordToGuess: "bueno/a", hint: "dobrý", category: ["pridavnaJm"] },
  { wordToGuess: "cada", hint: "každý", category: ["pridavnaJm"] },
  { wordToGuess: "cadena, la", hint: "řetěz", category: ["podstatnaJm"] },
  { wordToGuess: "caja, la", hint: "krabice", category: ["podstatnaJm"] },
  { wordToGuess: "calle, la", hint: "ulice", category: ["podstatnaJm", "mista"] },
  { wordToGuess: "cámara, la", hint: "fotoaparát", category: ["cinnost"] },
  { wordToGuess: "camarero/a, el/la", hint: "číšník", category: ["profese"] },
  { wordToGuess: "capital, la", hint: "hlavní město", category: ["mista"] },
  { wordToGuess: "casco, el", hint: "historické centrum, helma", category: ["mista"] },
  { wordToGuess: "casilla, la", hint: "rámeček, mezera", category: ["podstatnaJm"] },
  { wordToGuess: "castaño/a", hint: "hnědý", category: ["barvy"] },
  { wordToGuess: "Chile", hint: "Chile", category: ["zeme"] },
  { wordToGuess: "chileno/a", hint: "Chilan", category: ["zeme"] },
  { wordToGuess: "ciudad, la", hint: "město", category: ["mista"] },
  { wordToGuess: "claro/a", hint: "jasný, světlý", category: ["pridavnaJm"] },
  { wordToGuess: "clase, la", hint: "třída", category: ["podstatnaJm", "mista"] },
  { wordToGuess: "clínica, la", hint: "klinika", category: ["profese", "mista"] },
  { wordToGuess: "coche, el", hint: "auto", category: ["podstatnaJm"] },
  { wordToGuess: "cocinero/a, el/la", hint: "kuchař", category: ["profese"] },
  { wordToGuess: "Colombia", hint: "Kolumbie", category: ["zeme"] },
  { wordToGuess: "colombiano/a", hint: "Kolumbijec", category: ["zeme"] },
  { wordToGuess: "cómo", hint: "jak", category: ["zajmeno"] },
  {
    wordToGuess: "compañero/a, el/la",
    hint: "kamarád, spolužák (de clase)",
    category: ["podstatnaJm"],
  },
  { wordToGuess: "completo/a", hint: "kompletní", category: ["pridavnaJm"] },
  { wordToGuess: "confirmar", hint: "potvrdit", category: ["cinnost"] },
  { wordToGuess: "congreso, el", hint: "kongres", category: ["podstatnaJm"] },
  { wordToGuess: "conocer", hint: "vědět, znát", category: ["cinnost"] },
  { wordToGuess: "contestar", hint: "odpovědět", category: ["cinnost"] },
  { wordToGuess: "correcto/a", hint: "správný", category: ["pridavnaJm"] },
  { wordToGuess: "corregir", hint: "opravit", category: ["cinnost"] },
  { wordToGuess: "corresponder", hint: "odpovědět", category: ["cinnost"] },
  { wordToGuess: "correspondiente", hint: "odpovídající", category: ["pridavnaJm"] },
  { wordToGuess: "cuadro, el", hint: "obrázek", category: ["podstatnaJm"] },
  { wordToGuess: "cuál", hint: "jaký, který", category: ["zajmeno"] },
  { wordToGuess: "cuanto", hint: "kolik", category: ["zajmeno", "cisla"] },
  { wordToGuess: "cuatro", hint: "4", category: ["cisla"] },
  { wordToGuess: "cultural", hint: "kulturní", category: ["pridavnaJm"] },
  { wordToGuess: "dar", hint: "dát", category: ["cinnost"] },
  { wordToGuess: "dato, el", hint: "datum", category: ["cas"] },
  { wordToGuess: "dedicar", hint: "věnovat, dedikovat", category: ["cinnost"] },
  { wordToGuess: "delante (de)", hint: "před", category: ["umisteni"] },
  { wordToGuess: "deletrear", hint: "vyhláskovat", category: ["cinnost"] },
  { wordToGuess: "derecha, la", hint: "pravý", category: ["umisteni"] },
  { wordToGuess: "después (de)", hint: "po", category: ["zajmeno"] },
  { wordToGuess: "diálogo, el", hint: "dialog", category: ["podstatnaJm"] },
  { wordToGuess: "día, el", hint: "den", category: ["cas", "podstatnaJm"] },
  { wordToGuess: "dibujo, el", hint: "obrázek", category: ["podstatnaJm"] },
  { wordToGuess: "distinguir", hint: "odlišit", category: ["cinnost"] },
  { wordToGuess: "distinto/a", hint: "odlišný", category: ["pridavnaJm"] },
  { wordToGuess: "domicilio, el", hint: "bydliště", category: ["mista"] },
  { wordToGuess: "dónde", hint: "kde", category: ["zajmeno"] },
  { wordToGuess: "Ecuador", hint: "Ekvádor", category: ["zeme"] },
  { wordToGuess: "ejemplo, el", hint: "příklad", category: ["podstatnaJm"] },
  { wordToGuess: "ejercicio, el", hint: "cvičení", category: ["podstatnaJm"] },
  { wordToGuess: "empleado/a, el/la", hint: "zaměstnanec", category: ["podstatnaJm", "profese"] },
  { wordToGuess: "empresa, la", hint: "firma", category: ["podstatnaJm", "mista", "profese "] },
  { wordToGuess: "entre", hint: "mezi", category: ["umisteni"] },
  { wordToGuess: "entrevista, la", hint: "rozhovor", category: ["cinnost"] },
  { wordToGuess: "entrevistador/a, el/la", hint: "dotazovatel", category: ["profese"] },
  { wordToGuess: "escuela, la", hint: "škola", category: ["podstatnaJm", "mista"] },
  { wordToGuess: "España", hint: "Španělsko", category: ["zeme"] },
  { wordToGuess: "español/-a", hint: "Španěl", category: ["zeme"] },
  { wordToGuess: "estadounidense", hint: "z USA", category: ["zeme"] },
  { wordToGuess: "estudiante, el/la", hint: "student", category: ["profese"] },
  { wordToGuess: "estudiar", hint: "studovat", category: ["profese"] },
  { wordToGuess: "famoso/a", hint: "známý", category: ["pridavnaJm"] },
  { wordToGuess: "femenino/a", hint: "ženský", category: ["pridavnaJm"] },
  { wordToGuess: "ficha, la", hint: "formulář", category: ["podstatnaJm"] },
  { wordToGuess: "fontanero/a, el/la", hint: "instalatér", category: ["profese"] },
  { wordToGuess: "forma, la", hint: "forma", category: ["podstatnaJm"] },
  { wordToGuess: "foto, la", hint: "fotka", category: ["podstatnaJm"] },
  { wordToGuess: "frase, la", hint: "věta", category: ["podstatnaJm"] },
  { wordToGuess: "gente, la", hint: "lidé", category: ["podstatnaJm"] },
  { wordToGuess: "gorra, la", hint: "čepice", category: ["podstatnaJm"] },
  { wordToGuess: "gracias", hint: "děkuji", category: ["podstatnaJm"] },
  { wordToGuess: "Grecia", hint: "Řecko", category: ["zeme"] },
  { wordToGuess: "griego/a", hint: "Řek", category: ["zeme"] },
  { wordToGuess: "grupo, el", hint: "skupina", category: ["podstatnaJm"] },
  { wordToGuess: "gustar", hint: "mít rád", category: ["cinnost"] },
  { wordToGuess: "habitante, el", hint: "obyvatel", category: ["zeme"] },
  { wordToGuess: "hablar", hint: "mluvit", category: ["cinnost"] },
  { wordToGuess: "hasta", hint: "až do", category: ["cas"] },
  { wordToGuess: "hay", hint: "je, existuje", category: ["zajmeno"] },
  { wordToGuess: "herramienta, la", hint: "nástroj", category: ["podstatnaJm"] },
  { wordToGuess: "hispanoamérica", hint: "Latinská Amerika", category: ["zeme"] },
  { wordToGuess: "hola", hint: "ahoj", category: ["podstatnaJm"] },
  { wordToGuess: "hospital, el", hint: "nemocnice", category: ["podstatnaJm", "profese", "mista"] },
  { wordToGuess: "hotel, el", hint: "hotel", category: ["podstatnaJm", "mista", "profese"] },
  { wordToGuess: "identificación, la", hint: "identifikace", category: ["cinnost"] },
  { wordToGuess: "idioma, el", hint: "jazyk", category: ["podstatnaJm"] },
  { wordToGuess: "igual", hint: "stejný", category: ["pridavnaJm"] },
  { wordToGuess: "importante", hint: "důležitý", category: ["pridavnaJm"] },
  { wordToGuess: "información, la", hint: "informace", category: ["podstatnaJm"] },
  { wordToGuess: "informador/-a, el/la", hint: "informátor, zpravodaj", category: ["profese"] },
  { wordToGuess: "inglés/a", hint: "Angličan", category: ["zeme"] },
  { wordToGuess: "integrado/a", hint: "začleněný", category: ["pridavnaJm"] },
  { wordToGuess: "intentar", hint: "zkusit", category: ["cinnost"] },
  { wordToGuess: "internacional", hint: "mezinárodní", category: ["zeme"] },
  { wordToGuess: "interrogación, la", hint: "otázka", category: ["podstatnaJm"] },
  { wordToGuess: "inventar", hint: "vymyslet, vytvořit", category: ["cinnost"] },
  { wordToGuess: "iraní", hint: "Íránec", category: ["zeme"] },
  { wordToGuess: "Italia", hint: "Itálie", category: ["zeme"] },
  { wordToGuess: "italiano/a", hint: "Ital", category: ["zeme"] },
  { wordToGuess: "izquierda, la", hint: "levý", category: ["umisteni", "pridavnaJm"] },
  { wordToGuess: "japonés/-a", hint: "Japonec", category: ["zeme"] },
  { wordToGuess: "lengua, la", hint: "jazyk", category: ["podstatnaJm"] },
  { wordToGuess: "letra, la", hint: "písmeno", category: ["podstatnaJm"] },
  { wordToGuess: "mano, la", hint: "ruka", category: ["podstatnaJm"] },
  { wordToGuess: "mapa, el", hint: "mapa", category: ["podstatnaJm"] },
  { wordToGuess: "marca, la", hint: "značka, stopa", category: ["podstatnaJm"] },
  { wordToGuess: "mal", hint: "špantně", category: ["pridavnaJm"] },
  { wordToGuess: "más", hint: "více", category: ["pridavnaJm"] },
  { wordToGuess: "masculino/a", hint: "mužský", category: ["pridavnaJm"] },
  { wordToGuess: "médico/a", hint: "lékař", category: ["profese"] },
  { wordToGuess: "mencionar", hint: "zmínit", category: ["cinnost"] },
  { wordToGuess: "mexicano/a", hint: "Mexičan", category: ["zeme"] },
  { wordToGuess: "México", hint: "Mexiko", category: ["zeme"] },
  { wordToGuess: "micrófono, el", hint: "mikrofon", category: ["podstatnaJm"] },
  { wordToGuess: "muy", hint: "velmi", category: ["pridavnaJm"] },
  { wordToGuess: "nacionalidad, la", hint: "národnost", category: ["zeme"] },
  { wordToGuess: "Nicaragua", hint: "Nicaragua", category: ["zeme"] },
  { wordToGuess: "Nicaragüense", hint: "Nikaragujec", category: ["zeme"] },
  { wordToGuess: "nombre, el", hint: "jméno", category: ["podstatnaJm"] },
  { wordToGuess: "norteamericano/a", hint: "Severoameričan", category: ["zeme"] },
  { wordToGuess: "nuevo/a", hint: "nový", category: ["pridavnaJm"] },
  { wordToGuess: "objeto, el", hint: "objekt", category: ["podstatnaJm"] },
  { wordToGuess: "ocupación, la", hint: "činnost, aktivita", category: ["profese"] },
  { wordToGuess: "ocupar", hint: "zabývat se, zaměstnat", category: ["profese"] },
  { wordToGuess: "oficial", hint: "oficiální", category: ["pridavnaJm"] },
  { wordToGuess: "oficina, la", hint: "kancelář", category: ["mista", "profese"] },
  { wordToGuess: "oído, el", hint: "sluch", category: ["podstatnaJm"] },
  { wordToGuess: "opción, la", hint: "možnost", category: ["podstatnaJm"] },
  { wordToGuess: "ordenar", hint: "srovnat, seřadit", category: ["cinnost"] },
  { wordToGuess: "otro/a", hint: "jiný, další", category: ["pridavnaJm"] },
  { wordToGuess: "paciente, el", hint: "pacient", category: ["profese"] },
  { wordToGuess: "país, el", hint: "stát", category: ["cinnost"] },
  { wordToGuess: "palabra, la", hint: "slovo", category: ["podstatnaJm"] },
  { wordToGuess: "para", hint: "aby, pro", category: ["zajmeno "] },
  { wordToGuess: "pareja, la", hint: "partner", category: ["podstatnaJm"] },
  { wordToGuess: "paréntesis, el", hint: "závorky", category: ["podstatnaJm"] },
  { wordToGuess: "participante, el", hint: "účastník", category: ["podstatnaJm"] },
  { wordToGuess: "pedir", hint: "prosit, žádat", category: ["cinnost"] },
  { wordToGuess: "peluquería, la", hint: "kadeřnictví", category: ["mista", "profese"] },
  { wordToGuess: "peluquero/a, el/la", hint: "kadeřník", category: ["profese"] },
  { wordToGuess: "pequeño/a", hint: "malý", category: ["pridavnaJm"] },
  { wordToGuess: "perfecto/a", hint: "perfektní", category: ["pridavnaJm"] },
  { wordToGuess: "periódico, el", hint: "noviny", category: ["podstatnaJm", "profese"] },
  { wordToGuess: "periodismo, el", hint: "novinařina", category: ["profese"] },
  { wordToGuess: "periodista, el/la", hint: "novinář", category: ["profese"] },
  { wordToGuess: "pero", hint: "ale", category: ["zajmeno"] },
  { wordToGuess: "perro, el", hint: "pes", category: ["podstatnaJm"] },
  { wordToGuess: "persona, la", hint: "osoba", category: ["podstatnaJm"] },
  { wordToGuess: "personal", hint: "personál", category: ["podstatnaJm", "profese"] },
  { wordToGuess: "personalidad, la", hint: "osobnost", category: ["podstatnaJm"] },
  { wordToGuess: "Perú", hint: "Peru", category: ["zeme"] },
  { wordToGuess: "peruano/a", hint: "Peruánec", category: ["zeme"] },
  { wordToGuess: "pintor/-a, el/la", hint: "malíř", category: ["profese"] },
  { wordToGuess: "piso, el", hint: "byt", category: ["podstatnaJm", "mista"] },
  { wordToGuess: "pizarra, la", hint: "tabule", category: ["podstatnaJm"] },
  { wordToGuess: "pizzería, la", hint: "pizzerie", category: ["podstatnaJm", "mista", "profese"] },
  { wordToGuess: "plano, el", hint: "plán", category: ["podstatnaJm"] },
  { wordToGuess: "población, la", hint: "osídlení, populace", category: ["podstatnaJm"] },
  { wordToGuess: "policía, la", hint: "policie", category: ["profese"] },
  { wordToGuess: "practicar", hint: "cvičit, praktikovat", category: ["cinnost"] },
  { wordToGuess: "pregunta, la", hint: "otázka", category: ["podstatnaJm"] },
  { wordToGuess: "preguntar", hint: "ptát se", category: ["cinnost"] },
  { wordToGuess: "presentar", hint: "představit", category: ["cinnost"] },
  { wordToGuess: "principio, el", hint: "začátek", category: ["podstatnaJm", "cas"] },
  { wordToGuess: "profesión, la", hint: "profese", category: ["profese"] },
  { wordToGuess: "profesor/-a, el/la", hint: "professor, učitel", category: ["profese"] },
  { wordToGuess: "pues", hint: "nuže, tak tedy", category: ["zajmeno"] },
  { wordToGuess: "punto, el", hint: "bod, tečka", category: ["podstatnaJm"] },
  { wordToGuess: "puntuación, la", hint: "interpunkce", category: ["podstatnaJm"] },
  { wordToGuess: "puntuar", hint: "obodovat", category: ["cinnost"] },
  { wordToGuess: "que", hint: "co", category: ["zajmeno"] },
  { wordToGuess: "reconocer", hint: "poznat", category: ["cinnost"] },
  { wordToGuess: "región, la", hint: "region", category: ["podstatnaJm", "mista"] },
  { wordToGuess: "relacionar", hint: "spojit", category: ["cinnost"] },
  { wordToGuess: "rellenar", hint: "vyplnit", category: ["cinnost"] },
  { wordToGuess: "responder", hint: "odpovědět", category: ["cinnost"] },
  { wordToGuess: "respuesta, la", hint: "odpověď", category: ["podstatnaJm"] },
  { wordToGuess: "restaurante, el", hint: "restaurace", category: ["mista", "profese"] },
  { wordToGuess: "saludar", hint: "pozdravit", category: ["cinnost"] },
  { wordToGuess: "significado, el", hint: "význam", category: ["podstatnaJm"] },
  { wordToGuess: "signo, el", hint: "znamení", category: ["podstatnaJm"] },
  { wordToGuess: "sin", hint: "bez", category: ["zajmeno"] },
  { wordToGuess: "sobre", hint: "o, na", category: ["zajmeno"] },
  { wordToGuess: "también", hint: "taky", category: ["zajmeno"] },
  { wordToGuess: "tarjeta, la", hint: "karta", category: ["podstatnaJm"] },
  { wordToGuess: "taxista, el/la", hint: "taxikář", category: ["profese"] },
  { wordToGuess: "tenista, el/la", hint: "tenista", category: ["profese"] },
  { wordToGuess: "termómetro, el", hint: "teploměr", category: ["podstatnaJm"] },
  { wordToGuess: "texto, el", hint: "text", category: ["podstatnaJm"] },
  { wordToGuess: "tiqué, el", hint: "lístek", category: ["podstatnaJm"] },
  { wordToGuess: "tienda, la", hint: "obchod", category: ["mista", "profese"] },
  { wordToGuess: "tijeras, las", hint: "nůžky", category: ["podstatnaJm"] },
  { wordToGuess: "todavía", hint: "ještě", category: ["zajmeno"] },
  { wordToGuess: "todo", hint: "vše", category: ["cisla"] },
  { wordToGuess: "trabajar", hint: "pracovat", category: ["cinnost"] },
  { wordToGuess: "trabajo, el", hint: "práce", category: ["cinnost", "profese"] },
  { wordToGuess: "tratar", hint: "pokusit se, snažit se", category: ["cinnost"] },
  { wordToGuess: "universidad, la", hint: "univerzita", category: ["mista"] },
  { wordToGuess: "usar", hint: "použít", category: ["cinnost"] },
  { wordToGuess: "vaso, el", hint: "sklenice", category: ["podstatnaJm"] },
  { wordToGuess: "vendedor/-a, el/la", hint: "prodavač", category: ["profese"] },
  { wordToGuess: "venezolano/a", hint: "Venezolan", category: ["zeme"] },
  { wordToGuess: "Venezuela", hint: "Venezuela", category: ["zeme"] },
  { wordToGuess: "verbo, el", hint: "sloveso", category: ["podstatnaJm"] },
  { wordToGuess: "veterinario/a", hint: "veterinář", category: ["profese"] },
  { wordToGuess: "vivir", hint: "žít", category: ["cinnost"] },
  { wordToGuess: "voz, la", hint: "hlas", category: ["podstatnaJm"] },
  { wordToGuess: "zoo(lógico), el", hint: "zoo", category: ["mista", "profese"] },
  { wordToGuess: "Rojo", hint: "červená", category: ["barvy"] },
  { wordToGuess: "Azul", hint: "Modrá", category: ["barvy"] },
  { wordToGuess: "Verde", hint: "Zelená", category: ["barvy"] },
  { wordToGuess: "Las frutas", hint: "Ovoce", category: ["jidlo"] },
  { wordToGuess: "Las manzanas", hint: "Jablka", category: ["jidlo"] },
  { wordToGuess: "Los melocotones", hint: "Broskve", category: ["jidlo"] },
  { wordToGuess: "Los limones", hint: "Citrony", category: ["jidlo"] },
  { wordToGuess: "Las fresas", hint: "Jahody", category: ["jidlo"] },
  { wordToGuess: "Las cerezas", hint: "Třešně", category: ["jidlo"] },
  { wordToGuess: "La sandía", hint: "Meloun (vodní)", category: ["jidlo"] },
  { wordToGuess: "Los plátanos", hint: "Banány", category: ["jidlo"] },
  { wordToGuess: "La piña", hint: "Ananas", category: ["jidlo"] },
  { wordToGuess: "El melón", hint: "Meloun (cukrový)", category: ["jidlo"] },
  { wordToGuess: "Las castañas", hint: "Kaštany", category: ["jidlo"] },
  { wordToGuess: "La uva", hint: "Hroznové víno", category: ["jidlo"] },
  { wordToGuess: "Los higos", hint: "Fíky", category: ["jidlo"] },
  { wordToGuess: "Las naranjas", hint: "Pomeranče", category: ["jidlo"] },
  { wordToGuess: "Las peras", hint: "Hrušky", category: ["jidlo"] },
  { wordToGuess: "Las mandarinas", hint: "Mandarinky", category: ["jidlo"] },
  { wordToGuess: "Las verduras", hint: "Zelenina", category: ["jidlo"] },
  { wordToGuess: "El pepino", hint: "Okurka", category: ["jidlo"] },
  { wordToGuess: "La lechuga", hint: "Hlávkový salát", category: ["jidlo"] },
  { wordToGuess: "Las zanahorias", hint: "Mrkve", category: ["jidlo"] },
  { wordToGuess: "Los tomates", hint: "Rajčata", category: ["jidlo"] },
  { wordToGuess: "Las cebollas", hint: "Cibule", category: ["jidlo"] },
  { wordToGuess: "Los calabacines", hint: "Cukety", category: ["jidlo"] },
  { wordToGuess: "Los pimientos", hint: "Papriky", category: ["jidlo"] },
  { wordToGuess: "Las patatas", hint: "Brambory", category: ["jidlo"] },
  { wordToGuess: "El arroz", hint: "Rýže", category: ["jidlo"] },
  { wordToGuess: "Los ajos", hint: "Česnek", category: ["jidlo"] },
  { wordToGuess: "Los guisantes", hint: "Hrášek", category: ["jidlo"] },
  { wordToGuess: "Las coles", hint: "Zelí", category: ["jidlo"] },
  { wordToGuess: "Las judías verdes", hint: "Zelené fazolky", category: ["jidlo"] },
  { wordToGuess: "Las berenjenas", hint: "Lilek", category: ["jidlo"] },
  { wordToGuess: "La calabaza", hint: "Dýně", category: ["jidlo"] },
  { wordToGuess: "La carne y los embutidos", hint: "Maso a uzeniny", category: ["jidlo"] },
  { wordToGuess: "El jamón", hint: "Šunka", category: ["jidlo"] },
  { wordToGuess: "El salchichón", hint: "Salám", category: ["jidlo"] },
  { wordToGuess: "Las salchichas", hint: "Párečky", category: ["jidlo"] },
  { wordToGuess: "La carne de vaca", hint: "Hovězí maso", category: ["jidlo"] },
  { wordToGuess: "La carne de ternera", hint: "Telecí maso", category: ["jidlo"] },
  { wordToGuess: "La carne de cerdo", hint: "Vepřové maso", category: ["jidlo"] },
  { wordToGuess: "La carne de cordero", hint: "Jehněčí maso", category: ["jidlo"] },
  { wordToGuess: "La carne de pollo", hint: "Kuřecí maso", category: ["jidlo"] },
  { wordToGuess: "El pescado", hint: "Ryby", category: ["jidlo"] },
  { wordToGuess: "La carpa", hint: "Kapr", category: ["jidlo"] },
  { wordToGuess: "El lucio", hint: "Štika", category: ["jidlo"] },
  { wordToGuess: "La anguila", hint: "Úhoř", category: ["jidlo"] },
  { wordToGuess: "La trucha", hint: "Pstruh", category: ["jidlo"] },
  { wordToGuess: "El salmón", hint: "Losos", category: ["jidlo"] },
  { wordToGuess: "La merluza", hint: "Mořská štika", category: ["jidlo"] },
  { wordToGuess: "El atún", hint: "Tuňák", category: ["jidlo"] },
  { wordToGuess: "Los pulpos", hint: "Chobotnice", category: ["jidlo"] },
  { wordToGuess: "Las sepias", hint: "Sépie", category: ["jidlo"] },
  { wordToGuess: "Los langostinos", hint: "Krevety (tygří)", category: ["jidlo"] },
  { wordToGuess: "Los dulces", hint: "Sladkosti", category: ["jidlo"] },
  { wordToGuess: "El helado", hint: "Zmrzlina", category: ["jidlo"] },
  { wordToGuess: "El chocolate", hint: "Čokoláda", category: ["jidlo"] },
  { wordToGuess: "Los pasteles", hint: "Dortíky", category: ["jidlo"] },
  { wordToGuess: "Los caramelos", hint: "Bonbóny", category: ["jidlo"] },
  { wordToGuess: "Los bonbones", hint: "Pralinky", category: ["jidlo"] },
  { wordToGuess: "Los chupa-chups", hint: "Lízátka", category: ["jidlo"] },
  { wordToGuess: "Las tartas", hint: "Dorty", category: ["jidlo"] },
  { wordToGuess: "Los productos lácteos", hint: "Mléčné výrobky", category: ["jidlo"] },
  { wordToGuess: "La leche", hint: "Mléko", category: ["jidlo"] },
  { wordToGuess: "El yogúr", hint: "Jogurt", category: ["jidlo"] },
  { wordToGuess: "La mantequilla", hint: "Máslo", category: ["jidlo"] },
  { wordToGuess: "El queso", hint: "Sýr", category: ["jidlo"] },
  { wordToGuess: "La guarnición", hint: "Příloha", category: ["jidlo"] },
  { wordToGuess: "La ensalada", hint: "Salát", category: ["jidlo"] },
  { wordToGuess: "La pasta", hint: "Těstoviny", category: ["jidlo"] },
  { wordToGuess: "Los espaguetis", hint: "Špagety", category: ["jidlo"] },
  { wordToGuess: "Las croquetas", hint: "Krokety", category: ["jidlo"] },
  { wordToGuess: "Las bebidas", hint: "Nápoje", category: ["jidlo"] },
  { wordToGuess: "El zumo de naranja", hint: "Pomerančový džus", category: ["jidlo"] },
  { wordToGuess: "El zumo de manzana", hint: "Jablečný džus", category: ["jidlo"] },
  { wordToGuess: "El zumo de pera", hint: "Hruškový džus", category: ["jidlo"] },
  { wordToGuess: "El zumo de piña", hint: "Ananasový džus", category: ["jidlo"] },
  { wordToGuess: "El zumo de melocotón", hint: "Broskvový džus", category: ["jidlo"] },
  { wordToGuess: "El café", hint: "Káva", category: ["jidlo"] },
  { wordToGuess: "El café negro", hint: "Černá káva", category: ["jidlo"] },
  { wordToGuess: "El café con leche", hint: "Káva s mlékem", category: ["jidlo"] },
  { wordToGuess: "El chocolate", hint: "Horká čokoláda", category: ["jidlo"] },
  { wordToGuess: "La cerveza", hint: "Pivo", category: ["jidlo"] },
  { wordToGuess: "El vino blanco", hint: "Bílé víno", category: ["jidlo"] },
  { wordToGuess: "El vino tinto", hint: "Červené víno", category: ["jidlo"] },
  { wordToGuess: "El vino rosado", hint: "Růžové víno", category: ["jidlo"] },
  { wordToGuess: "El agua sin gas", hint: "Neperlivá voda", category: ["jidlo"] },
  { wordToGuess: "El agua con gas", hint: "Perlivá voda", category: ["jidlo"] },
  { wordToGuess: "El agua mineral", hint: "Minerální voda", category: ["jidlo"] },
  { wordToGuess: "El agua de grifo", hint: "Kohoutková voda", category: ["jidlo"] },
  { wordToGuess: "El refresco", hint: "Limonáda / nealko nápoj", category: ["jidlo"] },
  { wordToGuess: "La ropa", hint: "Oblečení", category: ["obleceni"] },
  { wordToGuess: "una falda", hint: "Sukně", category: ["obleceni"] },
  { wordToGuess: "un vestido", hint: "Šaty", category: ["obleceni"] },
  { wordToGuess: "un traje de fiesta", hint: "Společenský oblek/šaty", category: ["obleceni"] },
  { wordToGuess: "una blusa", hint: "Halenka", category: ["obleceni"] },
  { wordToGuess: "una camiseta", hint: "Tričko", category: ["obleceni"] },
  { wordToGuess: "una camisa", hint: "Košile", category: ["obleceni"] },
  { wordToGuess: "un jersey", hint: "Svetřík", category: ["obleceni"] },
  { wordToGuess: "un jersey de cuello alto", hint: "Rolák", category: ["obleceni"] },
  { wordToGuess: "un chaleco", hint: "Vesta", category: ["obleceni"] },
  { wordToGuess: "una sudadera", hint: "Mikina", category: ["obleceni"] },
  { wordToGuess: "un abrigo", hint: "Kabát", category: ["obleceni"] },
  { wordToGuess: "una chaqueta", hint: "Sako / bunda", category: ["obleceni"] },
  { wordToGuess: "una cazadora", hint: "Bunda (větrovka)", category: ["obleceni"] },
  { wordToGuess: "una gabardina", hint: "Plášť / trenčkot", category: ["obleceni"] },
  { wordToGuess: "una corbata", hint: "Kravata", category: ["obleceni"] },
  { wordToGuess: "un paňuelo", hint: "Šátek", category: ["obleceni"] },
  { wordToGuess: "una bufanda", hint: "Šála", category: ["obleceni"] },
  { wordToGuess: "una cinta", hint: "Stuha / čelenka", category: ["obleceni"] },
  { wordToGuess: "un chal", hint: "Šál / přehoz", category: ["obleceni"] },
  { wordToGuess: "un cinturón", hint: "Pásek", category: ["obleceni"] },
  { wordToGuess: "un sombrero", hint: "Klobouk", category: ["obleceni"] },
  { wordToGuess: "unas gafas de sol", hint: "Sluneční brýle", category: ["obleceni"] },
  { wordToGuess: "una gorra", hint: "Kšiltovka", category: ["obleceni"] },
  { wordToGuess: "unos guantes", hint: "Rukavice", category: ["obleceni"] },
  { wordToGuess: "un gorro", hint: "Čepice", category: ["obleceni"] },
  { wordToGuess: "una boina", hint: "Baskická čepice / baret", category: ["obleceni"] },
  { wordToGuess: "un traje", hint: "Oblek", category: ["obleceni"] },
  { wordToGuess: "un traje de chaqueta", hint: "Kostým / oblek se sakem", category: ["obleceni"] },
  { wordToGuess: "unos pantalones", hint: "Kalhoty", category: ["obleceni"] },
  { wordToGuess: "unos vaqueros", hint: "Džíny", category: ["obleceni"] },
  { wordToGuess: "unos pantalones cortos", hint: "Kraťasy", category: ["obleceni"] },
  { wordToGuess: "un chándal", hint: "Tepláková souprava", category: ["obleceni"] },
  { wordToGuess: "unos zapatos", hint: "Boty", category: ["obleceni"] },
  {
    wordToGuess: "unos zapatos de tacón",
    hint: "Lodičky / boty na podpatku",
    category: ["obleceni"],
  },
  { wordToGuess: "unas sandalias", hint: "Sandály", category: ["obleceni"] },
  { wordToGuess: "unas botas", hint: "Kozačky / boty", category: ["obleceni"] },
  { wordToGuess: "unas deportivas", hint: "Sportovní boty", category: ["obleceni"] },
  { wordToGuess: "unas zapatillas", hint: "Tenisky / pantofle", category: ["obleceni"] },
  { wordToGuess: "unos calcetines", hint: "Ponožky", category: ["obleceni"] },
  { wordToGuess: "unas medias", hint: "Punčochy", category: ["obleceni"] },
  { wordToGuess: "las joyas", hint: "Šperky", category: ["obleceni"] },
  { wordToGuess: "un collar", hint: "Náhrdelník", category: ["obleceni"] },
  { wordToGuess: "un anillo", hint: "Prsten", category: ["obleceni"] },
  { wordToGuess: "una cadena", hint: "Řetízek", category: ["obleceni"] },
  { wordToGuess: "una pulsera", hint: "Náramek", category: ["obleceni"] },
  { wordToGuess: "unos pendientes", hint: "Náušnice", category: ["obleceni"] },
  {
    wordToGuess: "abrir",
    hint: "otevřít",
    category: ["lekce5"],
  },
  {
    wordToGuess: "acabado/a",
    hint: "dokončený/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "aceite, el",
    hint: "olej",
    category: ["lekce5"],
  },
  {
    wordToGuess: "acentuado/a",
    hint: "zdůrazněný/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "actividad, la",
    hint: "aktivita",
    category: ["lekce5"],
  },
  {
    wordToGuess: "acuerdo, el",
    hint: "dohoda",
    category: ["lekce5"],
  },
  {
    wordToGuess: "adivinado/a",
    hint: "uhodnutý/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "aduana, la",
    hint: "celnice",
    category: ["lekce5"],
  },
  {
    wordToGuess: "aeropuerto, el",
    hint: "letiště",
    category: ["lekce5"],
  },
  {
    wordToGuess: "alternativa, la",
    hint: "alternativa",
    category: ["lekce5"],
  },
  {
    wordToGuess: "alusivo/a",
    hint: "narážející, odkazující",
    category: ["lekce5"],
  },
  {
    wordToGuess: "América",
    hint: "Amerika",
    category: ["lekce5"],
  },
  {
    wordToGuess: "amurallado/a",
    hint: "opevněný/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "andando/a",
    hint: "jdoucí (pěšky)",
    category: ["lekce5"],
  },
  {
    wordToGuess: "anterioridad, la",
    hint: "předchozí období",
    category: ["lekce5"],
  },
  {
    wordToGuess: "antigüedad, la",
    hint: "starověk, stáří",
    category: ["lekce5"],
  },
  {
    wordToGuess: "aparcamiento, el",
    hint: "parkoviště",
    category: ["lekce5"],
  },
  {
    wordToGuess: "aprovechar",
    hint: "využít",
    category: ["lekce5"],
  },
  {
    wordToGuess: "arqueológico/a",
    hint: "archeologický/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "asiático/a",
    hint: "asijský/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "autobús, el",
    hint: "autobus",
    category: ["lekce5"],
  },
  {
    wordToGuess: "avenida, la",
    hint: "třída (městská)",
    category: ["lekce5"],
  },
  {
    wordToGuess: "ayuntamiento, el",
    hint: "radnice",
    category: ["lekce5"],
  },
  {
    wordToGuess: "balcón, el",
    hint: "balkón",
    category: ["lekce5"],
  },
  {
    wordToGuess: "cafetería, la",
    hint: "kavárna",
    category: ["lekce5"],
  },
  {
    wordToGuess: "callejero, el",
    hint: "uliční plán / plán města",
    category: ["lekce5"],
  },
  {
    wordToGuess: "carne, la",
    hint: "maso",
    category: ["lekce5"],
  },
  {
    wordToGuess: "carnicería, la",
    hint: "řeznictví",
    category: ["lekce5"],
  },
  {
    wordToGuess: "cercanía, la",
    hint: "blízkost, okolí",
    category: ["lekce5"],
  },
  {
    wordToGuess: "cerrar",
    hint: "zavřít",
    category: ["lekce5"],
  },
  {
    wordToGuess: "charcutería, la",
    hint: "obchod s uzeninami",
    category: ["lekce5"],
  },
  {
    wordToGuess: "cien",
    hint: "sto",
    category: ["lekce5"],
  },
  {
    wordToGuess: "cítrico, el",
    hint: "citrusový strom",
    category: ["lekce5"],
  },
  {
    wordToGuess: "colegio, el",
    hint: "škola",
    category: ["lekce5"],
  },
  {
    wordToGuess: "colonial",
    hint: "koloniální",
    category: ["lekce5"],
  },
  {
    wordToGuess: "comercial",
    hint: "obchodní",
    category: ["lekce5"],
  },
  {
    wordToGuess: "comercio",
    hint: "obchod",
    category: ["lekce5"],
  },
  {
    wordToGuess: "completamente",
    hint: "zcela, úplně",
    category: ["lekce5"],
  },
  {
    wordToGuess: "conocido/a",
    hint: "známý/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "conseguir",
    hint: "dosáhnout, získat",
    category: ["lekce5"],
  },
  {
    wordToGuess: "consulta, la",
    hint: "konzultace, ordinace (lékařská)",
    category: ["lekce5"],
  },
  {
    wordToGuess: "consultar",
    hint: "poradit se",
    category: ["lekce5"],
  },
  {
    wordToGuess: "contar",
    hint: "vyprávět, počítat",
    category: ["lekce5"],
  },
  {
    wordToGuess: "convento, el",
    hint: "klášter",
    category: ["lekce5"],
  },
  {
    wordToGuess: "correspondencia, la",
    hint: "korespondence",
    category: ["lekce5"],
  },
  {
    wordToGuess: "cruz, la",
    hint: "kříž",
    category: ["lekce5"],
  },
  {
    wordToGuess: "cruzar",
    hint: "přejít, překročit",
    category: ["lekce5"],
  },
  {
    wordToGuess: "cuarto, el",
    hint: "pokoj",
    category: ["lekce5"],
  },
  {
    wordToGuess: "cuatrocientos",
    hint: "čtyři sta",
    category: ["lekce5"],
  },
  {
    wordToGuess: "desconocido/a",
    hint: "neznámý/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "diferenciar",
    hint: "rozlišovat",
    category: ["lekce5"],
  },
  {
    wordToGuess: "digital",
    hint: "digitální",
    category: ["lekce5"],
  },
  {
    wordToGuess: "distancia",
    hint: "vzdálenost",
    category: ["lekce5"],
  },
  {
    wordToGuess: "documento, el",
    hint: "dokument",
    category: ["lekce5"],
  },
  {
    wordToGuess: "domingo",
    hint: "neděle",
    category: ["lekce5"],
  },
  {
    wordToGuess: "doscientos",
    hint: "dvě stě",
    category: ["lekce5"],
  },
  {
    wordToGuess: "entender",
    hint: "rozumět",
    category: ["lekce5"],
  },
  {
    wordToGuess: "entonces",
    hint: "tehdy, potom",
    category: ["lekce5"],
  },
  {
    wordToGuess: "época, la",
    hint: "epocha, období",
    category: ["lekce5"],
  },
  {
    wordToGuess: "escapada, la",
    hint: "únik, výlet (krátký)",
    category: ["lekce5"],
  },
  {
    wordToGuess: "espalda, la",
    hint: "záda",
    category: ["lekce5"],
  },
  {
    wordToGuess: "especial",
    hint: "speciální",
    category: ["lekce5"],
  },
  {
    wordToGuess: "espera, la",
    hint: "čekání",
    category: ["lekce5"],
  },
  {
    wordToGuess: "establecimiento, el",
    hint: "zařízení, podnik",
    category: ["lekce5"],
  },
  {
    wordToGuess: "estación, la",
    hint: "stanice, nádraží",
    category: ["lekce5"],
  },
  {
    wordToGuess: "estratégico/a",
    hint: "strategický/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "excepto",
    hint: "kromě",
    category: ["lekce5"],
  },
  {
    wordToGuess: "existencia, la",
    hint: "existence",
    category: ["lekce5"],
  },
  {
    wordToGuess: "exportación, la",
    hint: "export",
    category: ["lekce5"],
  },
  {
    wordToGuess: "fácil",
    hint: "snadný",
    category: ["lekce5"],
  },
  {
    wordToGuess: "ferrocarril, el",
    hint: "železnice",
    category: ["lekce5"],
  },
  {
    wordToGuess: "finalmente",
    hint: "nakonec",
    category: ["lekce5"],
  },
  {
    wordToGuess: "floristería, la",
    hint: "květinářství",
    category: ["lekce5"],
  },
  {
    wordToGuess: "fortaleza, la",
    hint: "pevnost, síla",
    category: ["lekce5"],
  },
  {
    wordToGuess: "fuente, la",
    hint: "pramen, fontána",
    category: ["lekce5"],
  },
  {
    wordToGuess: "fundación, la",
    hint: "založení",
    category: ["lekce5"],
  },
  {
    wordToGuess: "fundado/a",
    hint: "založený/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "gasolinera, la",
    hint: "čerpací stanice",
    category: ["lekce5"],
  },
  {
    wordToGuess: "gira, la",
    hint: "turné",
    category: ["lekce5"],
  },
  {
    wordToGuess: "guiado/a",
    hint: "vedený/á (např. prohlídka)",
    category: ["lekce5"],
  },
  {
    wordToGuess: "hambre, el",
    hint: "hlad",
    category: ["lekce5"],
  },
  {
    wordToGuess: "histórico/a",
    hint: "historický/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "horario, el",
    hint: "otevírací doba / rozvrh",
    category: ["lekce5"],
  },
  {
    wordToGuess: "hortaliza, la",
    hint: "zelenina",
    category: ["lekce5"],
  },
  {
    wordToGuess: "humanidad, la",
    hint: "lidstvo",
    category: ["lekce5"],
  },
  {
    wordToGuess: "ida, la",
    hint: "jízda tam, odjezd",
    category: ["lekce5"],
  },
  {
    wordToGuess: "iglesia, la",
    hint: "kostel",
    category: ["lekce5"],
  },
  {
    wordToGuess: "independencia, la",
    hint: "nezávislost",
    category: ["lekce5"],
  },
  {
    wordToGuess: "indeterminado/a",
    hint: "neurčitý/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "instrucción, la",
    hint: "instrukce",
    category: ["lekce5"],
  },
  {
    wordToGuess: "irregular",
    hint: "nepravidelný/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "kilómetro, el",
    hint: "kilometr",
    category: ["lekce5"],
  },
  {
    wordToGuess: "leche",
    hint: "mléko",
    category: ["lekce5"],
  },
  {
    wordToGuess: "lejos",
    hint: "daleko",
    category: ["lekce5"],
  },
  {
    wordToGuess: "libertad, la",
    hint: "svoboda",
    category: ["lekce5"],
  },
  {
    wordToGuess: "libre",
    hint: "volný/á, svobodný/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "librería, la",
    hint: "knihkupectví",
    category: ["lekce5"],
  },
  {
    wordToGuess: "línea, la",
    hint: "linka, čára",
    category: ["lekce5"],
  },
  {
    wordToGuess: "llegar a",
    hint: "dorazit do",
    category: ["lekce5"],
  },
  {
    wordToGuess: "madera, la",
    hint: "dřevo",
    category: ["lekce5"],
  },
  {
    wordToGuess: "mancha, la",
    hint: "skvrna",
    category: ["lekce5"],
  },
  {
    wordToGuess: "manecillas, las",
    hint: "ručičky (na hodinách)",
    category: ["lekce5"],
  },
  {
    wordToGuess: "manzana, la",
    hint: "jablko",
    category: ["lekce5"],
  },
  {
    wordToGuess: "mar, el",
    hint: "moře",
    category: ["lekce5"],
  },
  {
    wordToGuess: "marítimo/a",
    hint: "námořní, přímořský",
    category: ["lekce5"],
  },
  {
    wordToGuess: "medio/a",
    hint: "střední, prostřední",
    category: ["lekce5"],
  },
  {
    wordToGuess: "mencionado/a",
    hint: "zmíněný/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "mercado, el",
    hint: "trh",
    category: ["lekce5"],
  },
  {
    wordToGuess: "metálico/a",
    hint: "kovový/á, hotovost (v mincích)",
    category: ["lekce5"],
  },
  {
    wordToGuess: "mil",
    hint: "tisíc",
    category: ["lekce5"],
  },
  {
    wordToGuess: "militar",
    hint: "vojenský/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "minuto, el",
    hint: "minuta",
    category: ["lekce5"],
  },
  {
    wordToGuess: "modernista",
    hint: "modernistický, secesní",
    category: ["lekce5"],
  },
  {
    wordToGuess: "monasterio, el",
    hint: "klášter",
    category: ["lekce5"],
  },
  {
    wordToGuess: "museo, el",
    hint: "muzeum",
    category: ["lekce5"],
  },
  {
    wordToGuess: "nacional",
    hint: "národní",
    category: ["lekce5"],
  },
  {
    wordToGuess: "naval",
    hint: "námořní",
    category: ["lekce5"],
  },
  {
    wordToGuess: "neoclásico/a",
    hint: "neoklasicistní",
    category: ["lekce5"],
  },
  {
    wordToGuess: "novecientos",
    hint: "devět set",
    category: ["lekce5"],
  },
  {
    wordToGuess: "ochocientos",
    hint: "osm set",
    category: ["lekce5"],
  },
  {
    wordToGuess: "original",
    hint: "originální",
    category: ["lekce5"],
  },
  {
    wordToGuess: "panadería, la",
    hint: "pekárna",
    category: ["lekce5"],
  },
  {
    wordToGuess: "parada, la",
    hint: "zastávka",
    category: ["lekce5"],
  },
  {
    wordToGuess: "parque, el",
    hint: "park",
    category: ["lekce5"],
  },
  {
    wordToGuess: "patrimonio, el",
    hint: "dědictví, kulturní dědictví",
    category: ["lekce5"],
  },
  {
    wordToGuess: "penúltimo/a",
    hint: "předposlední",
    category: ["lekce5"],
  },
  {
    wordToGuess: "pescadería, la",
    hint: "rybárna (obchod s rybami)",
    category: ["lekce5"],
  },
  {
    wordToGuess: "pescado, el",
    hint: "ryba (ulovená, k jídlu)",
    category: ["lekce5"],
  },
  {
    wordToGuess: "petróleo, el",
    hint: "ropa",
    category: ["lekce5"],
  },
  {
    wordToGuess: "pino, el",
    hint: "borovice",
    category: ["lekce5"],
  },
  {
    wordToGuess: "pintar",
    hint: "malovat",
    category: ["lekce5"],
  },
  {
    wordToGuess: "piscina, la",
    hint: "bazén",
    category: ["lekce5"],
  },
  {
    wordToGuess: "planear",
    hint: "plánovat",
    category: ["lekce5"],
  },
  {
    wordToGuess: "precio, el",
    hint: "cena",
    category: ["lekce5"],
  },
  {
    wordToGuess: "procesión, la",
    hint: "procesí",
    category: ["lekce5"],
  },
  {
    wordToGuess: "producto, el",
    hint: "produkt",
    category: ["lekce5"],
  },
  {
    wordToGuess: "proyección, la",
    hint: "projekce, promítání",
    category: ["lekce5"],
  },
  {
    wordToGuess: "pueblo, el",
    hint: "vesnice, lid",
    category: ["lekce5"],
  },
  {
    wordToGuess: "puerta, la",
    hint: "dveře",
    category: ["lekce5"],
  },
  {
    wordToGuess: "puerto, el",
    hint: "přístav",
    category: ["lekce5"],
  },
  {
    wordToGuess: "quinientos",
    hint: "pět set",
    category: ["lekce5"],
  },
  {
    wordToGuess: "quiosco, el",
    hint: "stánek, kiosek",
    category: ["lekce5"],
  },
  {
    wordToGuess: "rectificar",
    hint: "opravit, napravit",
    category: ["lekce5"],
  },
  {
    wordToGuess: "refinado/a",
    hint: "vytříbený/á, elegantní",
    category: ["lekce5"],
  },
  {
    wordToGuess: "relacionar",
    hint: "spojit, uvést do souvislosti",
    category: ["lekce5"],
  },
  {
    wordToGuess: "reloj, el",
    hint: "hodiny, hodinky",
    category: ["lekce5"],
  },
  {
    wordToGuess: "reparación, la",
    hint: "oprava",
    category: ["lekce5"],
  },
  {
    wordToGuess: "resto, el",
    hint: "zbytek",
    category: ["lekce5"],
  },
  {
    wordToGuess: "revista, la",
    hint: "časopis",
    category: ["lekce5"],
  },
  {
    wordToGuess: "ropa, la",
    hint: "oblečení",
    category: ["lekce5"],
  },
  {
    wordToGuess: "saber",
    hint: "vědět, umět",
    category: ["lekce5"],
  },
  {
    wordToGuess: "sacar",
    hint: "vyndat",
    category: ["lekce5"],
  },
  {
    wordToGuess: "sección, la",
    hint: "oddělení, sekce",
    category: ["lekce5"],
  },
  {
    wordToGuess: "seiscientos",
    hint: "šest set",
    category: ["lekce5"],
  },
  {
    wordToGuess: "setecientos",
    hint: "sedm set",
    category: ["lekce5"],
  },
  {
    wordToGuess: "significar",
    hint: "znamenat",
    category: ["lekce5"],
  },
  {
    wordToGuess: "situado/a",
    hint: "umístěný/á, nacházející se",
    category: ["lekce5"],
  },
  {
    wordToGuess: "solución, la",
    hint: "řešení",
    category: ["lekce5"],
  },
  {
    wordToGuess: "tachar",
    hint: "škrtnout",
    category: ["lekce5"],
  },
  {
    wordToGuess: "taxi, el",
    hint: "taxi",
    category: ["lekce5"],
  },
  {
    wordToGuess: "toalla, la",
    hint: "ručník, osuška",
    category: ["lekce5"],
  },
  {
    wordToGuess: "transporte, el",
    hint: "doprava",
    category: ["lekce5"],
  },
  {
    wordToGuess: "tren, el",
    hint: "vlak",
    category: ["lekce5"],
  },
  {
    wordToGuess: "trescientos",
    hint: "tři sta",
    category: ["lekce5"],
  },
  {
    wordToGuess: "turismo, el",
    hint: "turistika",
    category: ["lekce5"],
  },
  {
    wordToGuess: "turista, el",
    hint: "turista",
    category: ["lekce5"],
  },
  {
    wordToGuess: "turístico/a",
    hint: "turistický/á",
    category: ["lekce5"],
  },
  {
    wordToGuess: "universitario/a",
    hint: "univerzitní",
    category: ["lekce5"],
  },
  {
    wordToGuess: "viaje, el",
    hint: "cesta, výlet",
    category: ["lekce5"],
  },
  {
    wordToGuess: "visita, la",
    hint: "návštěva",
    category: ["lekce5"],
  },
  {
    wordToGuess: "zapatería, la",
    hint: "obuvnictví",
    category: ["lekce5"],
  },
  {
    wordToGuess: "zapato, el",
    hint: "bota, střevíc",
    category: ["lekce5"],
  },
  {
    wordToGuess: "absolutamente",
    hint: "naprosto, absolutně",
    category: ["lekce6"],
  },
  {
    wordToGuess: "abundante",
    hint: "hojný, vydatný",
    category: ["lekce6"],
  },
  {
    wordToGuess: "acompañado/a",
    hint: "doprovázený/á",
    category: ["lekce6"],
  },
  {
    wordToGuess: "acuático/a",
    hint: "vodní",
    category: ["lekce6"],
  },
  {
    wordToGuess: "acostarse",
    hint: "jít si lehnout",
    category: ["lekce6"],
  },
  {
    wordToGuess: "afición, la",
    hint: "záliba, koníček",
    category: ["lekce6"],
  },
  {
    wordToGuess: "aficionado/a",
    hint: "nadšenec, fanoušek (dělající něco s nadšením)",
    category: ["lekce6"],
  },
  {
    wordToGuess: "agenda, la",
    hint: "diář",
    category: ["lekce6"],
  },
  {
    wordToGuess: "ahorrar",
    hint: "šetřit",
    category: ["lekce6"],
  },
  {
    wordToGuess: "alpinismo, el",
    hint: "horolezectví",
    category: ["lekce6"],
  },
  {
    wordToGuess: "andar",
    hint: "jít, chodit",
    category: ["lekce6"],
  },
  {
    wordToGuess: "aperitivo, el",
    hint: "aperitiv",
    category: ["lekce6"],
  },
  {
    wordToGuess: "árbitro, el",
    hint: "rozhodčí",
    category: ["lekce6"],
  },
  {
    wordToGuess: "atasco, el",
    hint: "dopravní zácpa",
    category: ["lekce6"],
  },
  {
    wordToGuess: "atletismo, el",
    hint: "atletika",
    category: ["lekce6"],
  },
  {
    wordToGuess: "avión, el",
    hint: "letadlo",
    category: ["lekce6"],
  },
  {
    wordToGuess: "baile, el",
    hint: "tanec",
    category: ["lekce6"],
  },
  {
    wordToGuess: "balón, el",
    hint: "míč",
    category: ["lekce6"],
  },
  {
    wordToGuess: "baloncesto, el",
    hint: "basketbal",
    category: ["lekce6"],
  },
  {
    wordToGuess: "bañarse",
    hint: "koupat se",
    category: ["lekce6"],
  },
  {
    wordToGuess: "bebida, la",
    hint: "nápoj",
    category: ["lekce6"],
  },
  {
    wordToGuess: "beicon, el",
    hint: "slanina",
    category: ["lekce6"],
  },
  {
    wordToGuess: "calor, el",
    hint: "teplo",
    category: ["lekce6"],
  },
  {
    wordToGuess: "caro/a",
    hint: "drahý/á",
    category: ["lekce6"],
  },
  {
    wordToGuess: "cazo, el",
    hint: "naběračka",
    category: ["lekce6"],
  },
  {
    wordToGuess: "cena, la",
    hint: "večeře",
    category: ["lekce6"],
  },
  {
    wordToGuess: "charlar",
    hint: "povídat si, klábosit",
    category: ["lekce6"],
  },
  {
    wordToGuess: "China",
    hint: "Čína",
    category: ["lekce6"],
  },
  {
    wordToGuess: "ciclismo, el",
    hint: "cyklistika",
    category: ["lekce6"],
  },
  {
    wordToGuess: "ciencia, la",
    hint: "věda",
    category: ["lekce6"],
  },
  {
    wordToGuess: "coger",
    hint: "vzít",
    category: ["lekce6"],
  },
  {
    wordToGuess: "coleccionar",
    hint: "sbírat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "comentar",
    hint: "komentovat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "competitivo/a",
    hint: "soutěživý/á",
    category: ["lekce6"],
  },
  {
    wordToGuess: "compra, la",
    hint: "nákup",
    category: ["lekce6"],
  },
  {
    wordToGuess: "común",
    hint: "společný, běžný",
    category: ["lekce6"],
  },
  {
    wordToGuess: "comunicar",
    hint: "komunikovat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "copa, la",
    hint: "sklenice",
    category: ["lekce6"],
  },
  {
    wordToGuess: "coser",
    hint: "šít",
    category: ["lekce6"],
  },
  {
    wordToGuess: "costumbre, la",
    hint: "zvyk",
    category: ["lekce6"],
  },
  {
    wordToGuess: "cronológico/a",
    hint: "chronologický/á",
    category: ["lekce6"],
  },
  {
    wordToGuess: "cuerda, la",
    hint: "provaz",
    category: ["lekce6"],
  },
  {
    wordToGuess: "cultivar",
    hint: "pěstovat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "dentista, el/la",
    hint: "zubař/ka",
    category: ["lekce6"],
  },
  {
    wordToGuess: "deporte, el",
    hint: "sport",
    category: ["lekce6"],
  },
  {
    wordToGuess: "desayuno, el",
    hint: "snídaně",
    category: ["lekce6"],
  },
  {
    wordToGuess: "descansar",
    hint: "odpočívat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "descanso, el",
    hint: "pauza",
    category: ["lekce6"],
  },
  {
    wordToGuess: "descubrir",
    hint: "objevit",
    category: ["lekce6"],
  },
  {
    wordToGuess: "despertador, el",
    hint: "budík",
    category: ["lekce6"],
  },
  {
    wordToGuess: "despertarse",
    hint: "probudit se",
    category: ["lekce6"],
  },
  {
    wordToGuess: "diario/a",
    hint: "denní",
    category: ["lekce6"],
  },
  {
    wordToGuess: "dormir",
    hint: "spát",
    category: ["lekce6"],
  },
  {
    wordToGuess: "ducha, la",
    hint: "sprcha",
    category: ["lekce6"],
  },
  {
    wordToGuess: "ducharse",
    hint: "sprchovat se",
    category: ["lekce6"],
  },
  {
    wordToGuess: "elaborar",
    hint: "vypracovat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "encantar",
    hint: "nadchnout, okouzlit",
    category: ["lekce6"],
  },
  {
    wordToGuess: "encuesta, la",
    hint: "anketa",
    category: ["lekce6"],
  },
  {
    wordToGuess: "entrenar",
    hint: "trénovat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "enviar",
    hint: "poslat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "escalar",
    hint: "lézt (po něčem)",
    category: ["lekce6"],
  },
  {
    wordToGuess: "espinacas, las",
    hint: "špenát",
    category: ["lekce6"],
  },
  {
    wordToGuess: "esquí, el",
    hint: "lyže",
    category: ["lekce6"],
  },
  {
    wordToGuess: "esquiar",
    hint: "lyžovat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "expresar",
    hint: "vyjádřit",
    category: ["lekce6"],
  },
  {
    wordToGuess: "favorito/a",
    hint: "oblíbený/á",
    category: ["lekce6"],
  },
  {
    wordToGuess: "ficción, la",
    hint: "fikce",
    category: ["lekce6"],
  },
  {
    wordToGuess: "figura, la",
    hint: "postava, figura",
    category: ["lekce6"],
  },
  {
    wordToGuess: "fotografía, la",
    hint: "fotografie",
    category: ["lekce6"],
  },
  {
    wordToGuess: "frecuencia, la",
    hint: "frekvence",
    category: ["lekce6"],
  },
  {
    wordToGuess: "frecuente",
    hint: "častý",
    category: ["lekce6"],
  },
  {
    wordToGuess: "frijoles, los",
    hint: "fazole",
    category: ["lekce6"],
  },
  {
    wordToGuess: "gimnasia, la",
    hint: "gymnastika",
    category: ["lekce6"],
  },
  {
    wordToGuess: "gimnasio, el",
    hint: "posilovna",
    category: ["lekce6"],
  },
  {
    wordToGuess: "gol, el",
    hint: "branka",
    category: ["lekce6"],
  },
  {
    wordToGuess: "golf, el",
    hint: "golf",
    category: ["lekce6"],
  },
  {
    wordToGuess: "hábito, el",
    hint: "zvyk",
    category: ["lekce6"],
  },
  {
    wordToGuess: "habitual",
    hint: "obvyklý, běžný",
    category: ["lekce6"],
  },
  {
    wordToGuess: "habitualmente",
    hint: "obvykle",
    category: ["lekce6"],
  },
  {
    wordToGuess: "huevo, el",
    hint: "vejce",
    category: ["lekce6"],
  },
  {
    wordToGuess: "ilustrativo/a",
    hint: "výmluvný, ilustrující",
    category: ["lekce6"],
  },
  {
    wordToGuess: "informe, el",
    hint: "zpráva",
    category: ["lekce6"],
  },
  {
    wordToGuess: "instituto, el",
    hint: "institut, střední škola (vyšší ročníky)",
    category: ["lekce6"],
  },
  {
    wordToGuess: "interactuar",
    hint: "interagovat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "invierno, el",
    hint: "zima",
    category: ["lekce6"],
  },
  {
    wordToGuess: "jardinería, la",
    hint: "zahradničení",
    category: ["lekce6"],
  },
  {
    wordToGuess: "judías, las",
    hint: "fazole",
    category: ["lekce6"],
  },
  {
    wordToGuess: "juerga, la",
    hint: "veselí, zábava",
    category: ["lekce6"],
  },
  {
    wordToGuess: "jugar",
    hint: "hrát",
    category: ["lekce6"],
  },
  {
    wordToGuess: "limpiar",
    hint: "uklízet",
    category: ["lekce6"],
  },
  {
    wordToGuess: "lista, la",
    hint: "seznam",
    category: ["lekce6"],
  },
  {
    wordToGuess: "mandar",
    hint: "poslat, přikázat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "mantequilla, la",
    hint: "máslo",
    category: ["lekce6"],
  },
  {
    wordToGuess: "mayoría, la",
    hint: "většina",
    category: ["lekce6"],
  },
  {
    wordToGuess: "mediodía, el",
    hint: "poledne",
    category: ["lekce6"],
  },
  {
    wordToGuess: "mensaje, el",
    hint: "zpráva",
    category: ["lekce6"],
  },
  {
    wordToGuess: "menú, el",
    hint: "jídelní lístek, menu",
    category: ["lekce6"],
  },
  {
    wordToGuess: "merendar",
    hint: "svačit",
    category: ["lekce6"],
  },
  {
    wordToGuess: "merienda, la",
    hint: "svačina",
    category: ["lekce6"],
  },
  {
    wordToGuess: "momento, el",
    hint: "okamžik",
    category: ["lekce6"],
  },
  {
    wordToGuess: "moneda, la",
    hint: "mince, měna",
    category: ["lekce6"],
  },
  {
    wordToGuess: "montañero/a, el/la",
    hint: "horolezec",
    category: ["lekce6"],
  },
  {
    wordToGuess: "motivo, el",
    hint: "důvod, motiv",
    category: ["lekce6"],
  },
  {
    wordToGuess: "municipal",
    hint: "městský",
    category: ["lekce6"],
  },
  {
    wordToGuess: "música, la",
    hint: "hudba",
    category: ["lekce6"],
  },
  {
    wordToGuess: "nadar",
    hint: "plavat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "natación, la",
    hint: "plavání",
    category: ["lekce6"],
  },
  {
    wordToGuess: "navegar",
    hint: "plavit se, navigovat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "necesitar",
    hint: "potřebovat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "nocturno/a",
    hint: "noční",
    category: ["lekce6"],
  },
  {
    wordToGuess: "ocupado/a",
    hint: "obsazený/á",
    category: ["lekce6"],
  },
  {
    wordToGuess: "oliva, la",
    hint: "oliva",
    category: ["lekce6"],
  },
  {
    wordToGuess: "ordenar",
    hint: "uspořádat, přikázat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "oscuro/a",
    hint: "tmavý/á",
    category: ["lekce6"],
  },
  {
    wordToGuess: "parecer",
    hint: "zdát se",
    category: ["lekce6"],
  },
  {
    wordToGuess: "partido, el",
    hint: "zápas, strana (politická)",
    category: ["lekce6"],
  },
  {
    wordToGuess: "pasear",
    hint: "jít na procházku",
    category: ["lekce6"],
  },
  {
    wordToGuess: "paseo, el",
    hint: "procházka",
    category: ["lekce6"],
  },
  {
    wordToGuess: "pausa, la",
    hint: "pauza",
    category: ["lekce6"],
  },
  {
    wordToGuess: "pelota, la",
    hint: "míč",
    category: ["lekce6"],
  },
  {
    wordToGuess: "permitir",
    hint: "dovolit",
    category: ["lekce6"],
  },
  {
    wordToGuess: "pescar",
    hint: "rybařit",
    category: ["lekce6"],
  },
  {
    wordToGuess: "picante",
    hint: "pálivý, ostrý",
    category: ["lekce6"],
  },
  {
    wordToGuess: "pincho, el",
    hint: "špíz",
    category: ["lekce6"],
  },
  {
    wordToGuess: "pista, la",
    hint: "dráha, piste (na lyžování), stopa",
    category: ["lekce6"],
  },
  {
    wordToGuess: "plato, el",
    hint: "talíř",
    category: ["lekce6"],
  },
  {
    wordToGuess: "playa, la",
    hint: "pláž",
    category: ["lekce6"],
  },
  {
    wordToGuess: "polideportivo, el",
    hint: "sportovní centrum",
    category: ["lekce6"],
  },
  {
    wordToGuess: "portero/a, el/la",
    hint: "vrátný/á, brankář/ka",
    category: ["lekce6"],
  },
  {
    wordToGuess: "postre, el",
    hint: "dezert",
    category: ["lekce6"],
  },
  {
    wordToGuess: "profesional",
    hint: "profesionální",
    category: ["lekce6"],
  },
  {
    wordToGuess: "pronto",
    hint: "brzy",
    category: ["lekce6"],
  },
  {
    wordToGuess: "proyecto, el",
    hint: "projekt",
    category: ["lekce6"],
  },
  {
    wordToGuess: "quedarse",
    hint: "zůstat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "rápido/a",
    hint: "rychlý/á",
    category: ["lekce6"],
  },
  {
    wordToGuess: "raqueta, la",
    hint: "tenisová raketa",
    category: ["lekce6"],
  },
  {
    wordToGuess: "rato, el",
    hint: "chvilka",
    category: ["lekce6"],
  },
  {
    wordToGuess: "recolectar",
    hint: "sbírat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "relajado/a",
    hint: "uvolněný/á",
    category: ["lekce6"],
  },
  {
    wordToGuess: "relajarse",
    hint: "uvolnit se, relaxovat",
    category: ["lekce6"],
  },
  {
    wordToGuess: "reunión, la",
    hint: "schůze, setkání",
    category: ["lekce6"],
  },
  {
    wordToGuess: "risa, la",
    hint: "smích",
    category: ["lekce6"],
  },
  {
    wordToGuess: "ruido, el",
    hint: "hluk",
    category: ["lekce6"],
  },
  {
    wordToGuess: "rutina, la",
    hint: "rutina",
    category: ["lekce6"],
  },
  {
    wordToGuess: "sano/a",
    hint: "zdravý/á",
    category: ["lekce6"],
  },
  {
    wordToGuess: "secreto/a",
    hint: "tajný/á",
    category: ["lekce6"],
  },
  {
    wordToGuess: "senderismo, el",
    hint: "turistika, pěší turistika",
    category: ["lekce6"],
  },
  {
    wordToGuess: "seta, la",
    hint: "hřib, houba",
    category: ["lekce6"],
  },
  {
    wordToGuess: "siesta, la",
    hint: "siesta (odpolední spánek)",
    category: ["lekce6"],
  },
  {
    wordToGuess: "similitud, la",
    hint: "podobnost",
    category: ["lekce6"],
  },
  {
    wordToGuess: "solamente",
    hint: "pouze, jen",
    category: ["lekce6"],
  },
  {
    wordToGuess: "sur",
    hint: "jih",
    category: ["lekce6"],
  },
  {
    wordToGuess: "tampoco",
    hint: "také ne",
    category: ["lekce6"],
  },
  {
    wordToGuess: "tapas, las",
    hint: "tapas (španělské malé pokrmy)",
    category: ["lekce6"],
  },
  {
    wordToGuess: "tapeo, el",
    hint: "chodit na tapas",
    category: ["lekce6"],
  },
  {
    wordToGuess: "té, el",
    hint: "čaj",
    category: ["lekce6"],
  },
  {
    wordToGuess: "tele, la",
    hint: "televize",
    category: ["lekce6"],
  },
  {
    wordToGuess: "tema, el",
    hint: "téma",
    category: ["lekce6"],
  },
  {
    wordToGuess: "terraza, la",
    hint: "terasa",
    category: ["lekce6"],
  },
  {
    wordToGuess: "texto, el",
    hint: "text",
    category: ["lekce6"],
  },
  {
    wordToGuess: "tiempo, el",
    hint: "čas, počasí",
    category: ["lekce6"],
  },
  {
    wordToGuess: "tirar",
    hint: "vyhodit, hodit",
    category: ["lekce6"],
  },
  {
    wordToGuess: "toalla, la",
    hint: "ručník",
    category: ["lekce6"],
  },
  {
    wordToGuess: "tortilla, la",
    hint: "tortilla (španělská omeleta)",
    category: ["lekce6"],
  },
  {
    wordToGuess: "tostada, la",
    hint: "toasts (opečený chléb)",
    category: ["lekce6"],
  },
  {
    wordToGuess: "tumbado/a",
    hint: "ležící",
    category: ["lekce6"],
  },
  {
    wordToGuess: "urbanización, la",
    hint: "sídliště",
    category: ["lekce6"],
  },
  {
    wordToGuess: "vestido, el",
    hint: "šaty",
    category: ["lekce6"],
  },
  {
    wordToGuess: "vestirse",
    hint: "obléknout se",
    category: ["lekce6"],
  },
  {
    wordToGuess: "vuelta, la",
    hint: "návrat, obrat",
    category: ["lekce6"],
  },
];

const params = new URLSearchParams(window.location.search);
const selectedCategory = params.get("category");

if (selectedCategory) {
  const filtered = flashcards.filter(
    (flashcard) => flashcard.category && flashcard.category.includes(selectedCategory)
  );
  if (filtered.length > 2) {
    flashcards = filtered;
  }
}

function shuffleCards(array) {
  let currentIndex = array.length;

  // While there remain elements to shuffle...
  while (currentIndex != 0) {
    // Pick a remaining element...
    let randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;

    // And swap it with the current element.
    [array[currentIndex], array[randomIndex]] = [array[randomIndex], array[currentIndex]];
  }
}

shuffleCards(flashcards);

let currentIndex = 0;

const hintElement = document.getElementById("hint");
const optionsElement = document.getElementById("options");

// Function to shuffle an array
function shuffle(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}

// Function to set up the quiz question
function setupQuestion() {
  const currentCard = flashcards[currentIndex];
  hintElement.textContent = currentCard.hint;

  // Prepare the options
  let options = [currentCard.wordToGuess];
  while (options.length < 3) {
    const randomWord = flashcards[Math.floor(Math.random() * flashcards.length)].wordToGuess;
    if (!options.includes(randomWord)) {
      options.push(randomWord);
    }
  }

  // Shuffle the options
  shuffle(options);

  // Clear and generate buttons
  optionsElement.innerHTML = "";
  options.forEach((option) => {
    const button = document.createElement("button");
    button.textContent = option;
    button.addEventListener("click", () => checkAnswer(button, currentCard.wordToGuess));
    optionsElement.appendChild(button);
  });
}

// Function to check the answer
function checkAnswer(button, correctAnswer) {
  if (button.textContent === correctAnswer) {
    button.classList.add("correct");
    setTimeout(() => {
      nextQuestion();
    }, 1000);
  } else {
    button.classList.add("incorrect");
  }
}

// Function to move to the next question
function nextQuestion() {
  currentIndex = (currentIndex + 1) % flashcards.length;
  setupQuestion();
}

// Initialize the quiz
setupQuestion();
